### ISSUE TITLE
Add Trusted Information Retrieval example

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1024]
After adding the Aggregator example (https://github.com/project-oak/oak/pull/626 https://github.com/project-oak/oak/pull/699), the next possible good example of Oak usage could Trusted Information Retrieval (similar to [Private Information Retrieval](https://en.wikipedia.org/wiki/Private_information_retrieval)).

I think the simplest PoC implementation could be:
- Server that contains coordinates of different example points of interest (shops, etc.)
- Client that sends its coordinates to the server and retrieves the nearest point of interest
- The whole database could be in-memory (as the initial PoC)
- [optional] Client authentication using TLS
- [optional] An Android client application

cc @project-oak/core

**Comment by tiziano88** [comment]
Nice plan!

FYI I think #1004 may be very useful here, to pass in the database to use for the lookups to the Oak Application, without having to recompile its source code every time.

As for interesting data sources, I have been looking around for something that could be used for this; it would be nice to have a list of Points Of Interest (POI) indexed by location, and being able to privately look them up based on the contents of an incoming request from a client, but I could not find such database yet. In the meanwhile though, I came across the [Transport For London API](https://api-portal.tfl.gov.uk/docs), which has, among others, an XML file with the availability of santander bikes for hire. Perhaps a nice initial demo would be to ingest this data in the application, and serve it to client in a private way. Then we can change it so that the Oak Application periodically downloads a fresh version of this file, which will require making sure that there is no interference between nodes that see secret data, and the node that downloads the data feed.
