### ISSUE TITLE
Move Node tests to be integration tests not unit tests

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1054]
As [commented elsewhere](https://github.com/project-oak/oak/issues/1038#issuecomment-636301473), the current Node tests are not really unit tests.  They don't require access to internal code from the Node, so they would all be better as [integration tests](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests), where the only `pub` thing needed from the Node would be the gRPC service message definitions.

**Comment by tiziano88** [comment]
+1, especially since those tests would depend on the `oak_runtime` directly, and testing the integration between the oak application and the runtime.

Unit tests would stay around for simple functionality such as testing individual functions or pieces of functionality within an application, but without needing the entire Oak runtime infrastructure.
