### ISSUE TITLE
Code generation for Oak Module gRPC interface

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#11]
Currently each Oak Module needs to explicitly dispatch gRPC calls based on the incoming gRPC method name, then deserialise the incoming request according to the appropriate protobuf type, and eventually serialise the outgoing response. All of this is very mechanical and in fact is fully determined by the gRPC service definition in the source protobuf file. We should rely on code generation to automate and hide all of this complexity from module authors.

A possible approach would be to start from https://github.com/stepancheg/grpc-rust and modify it so that it generates the server trait / base struct. Note we do not need to generate clients, nor any of the transport layer logic.

See 

https://github.com/project-oak/oak/blob/fbcd2353a29e8fb3549bc2d86815786df4992fe7/examples/running_average/src/lib.rs#L43-L64

**Comment by tiziano88** [comment]
For reference, this is how grpc-rust represents the server definition and its methods: 

https://github.com/stepancheg/grpc-rust/blob/9d104ea3ae1a3cecf94fea94e9b38d8941739c0a/grpc/src/server/mod.rs#L38-L65

**Comment by bprosnitz** [comment]
A few thoughts:
- I think I'll send a pull request for an update to one of the rpcs like hello_world.rs using a prototype of what the generated code will look like first, to make sure there is some agreement (at least for first version)
- Some concern integrating too deply with grpc-rust by forking the code, especially because there are some alternatives like prost that seem to be gaining popularity. Wondering if we should use the output of these libraries as inspiration but not necessarily fork.
- For code generation, there are a number of techniques. I was suggesting templating because I've worked on code generation for rpc in the [past](http://v.io) and that worked well. There are a number of other libraries that look compelling. For instance https://github.com/carllerche/codegen which uses a similar technique as LLVM (represent everything you want to write as data structures in code, make references to other values as variable references and then just print it out). The code generator (https://github.com/stepancheg/rust-protobuf/blob/master/protobuf-codegen/src/code_writer.rs) that grpc-rust uses seems ok but mostly just helpers for printing.

**Comment by bprosnitz** [comment]
An example of tower-grpc using the codegen library: https://github.com/tower-rs/tower-grpc/blob/master/tower-grpc-build/src/server.rs

**Comment by tiziano88** [comment]
- Good idea starting with producing and reviewing the expected generated code and then building the actual generator later. Also we can keep that artifact around as a test for the generator itself (serious TDD! :1st_place_medal: ).
- I meant more like we should copy-paste parts of their expected output code and / or implementation (assuming licenses allow it), rather than actually fork them on GitHub.
- I have not seen the codegen crate before, but it looks good (though not very popular). Alternatively I was thinking of using https://docs.rs/quote/0.6.11/quote/ which is already the standard library for code generation in Rust macros (e.g. [custom derive](https://doc.rust-lang.org/book/ch19-06-macros.html#how-to-write-a-custom-derive-macro)), but I think it is not particularly helpful at statically enforcing that the generated code has valid references, so it may make debugging harder (since we would only see some errors when compiling the generated code).

**Comment by tiziano88** [comment]
For reference, this is how grpc-rust encapsulates serialization and deserialization around handlers:

https://github.com/stepancheg/grpc-rust/blob/9d104ea3ae1a3cecf94fea94e9b38d8941739c0a/grpc/src/server/method.rs#L330-L369

**Comment by anghelcovici** [comment]
@daviddrysdale, we should close this, shouldn't we?

**Comment by daviddrysdale** [comment]
Yeah, I think we can close this &ndash; we have [code generation](https://github.com/project-oak/oak/blob/master/third_party/grpc-rust/grpc-compiler/src/codegen.rs) from the gRPC interface definition.  I'm sure it still needs tweaking and adaptation, but the general mechanism is there.
