### ISSUE TITLE
Monadic / effect system on top of Rust to help with dependency management

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1202]
I wonder if some of the work by the formal team may help with #1201. The Rust type system is not strong enough to enforce things such as as preventing (or controlling) side-effects in untrusted third party libraries, but Monadic and Effect systems in other programming languages mitigate this to some extent.

Perhaps there is something we could do to layer an effect system on top of the Rust type system?

So that, for instance, we could convince that, by passing a sensitive value to a third party library function, we would know for sure that the library cannot possibly perform any side effects with it (sending it over the network, storing it to disk). 

@alastairreid @satnam6502 is this something you think may be feasible at all?

**Comment by alastairreid** [comment]
I am not sure how usable monadic/effect annotations would be in Rust

- In a functional language or near-functional language like Haskell/ML, these work pretty well because there is so little state manipulation that calling out the small amount that does occur is a small annotation burden and adds significant value (because the surprise factor of the information is fairly high).

- In most Rust, I would expect that state is being modified by a large fraction of functions but also that a large fraction of functions do not modify state. So adding annotations to say that a function modifies state (default it does not) would be burdensome and changing the default to "it does modify state" would also be burdensome.

On the other hand, it sounds as though what you really want is an information flow analysis?
I think that there are two ways to go about this:

- Annotate the code directly with information flow annotations. This approach was tried in JIF (for Java) so there is experience that we could build on.  I am not sure whether this avoids the usability issues of monadic/effect annotations.

- Write information flow properties about particular functions and use a variant of model checking to check that the properties hold.  I have done something like this before in a previous project (with a different language).  I think this avoids the usability issues (because you only write properties for a small number of functions) but I am not sure whether this would scale.

**Comment by tiziano88** [comment]
I was imagining that the additional annotations would only control access to global mutable state, or unsafe code. Anything that is explicitly passed by reference or as an owned value to an untrusted function, should be assumed to be under control of the untrusted function. But currently even untrusted functions can get access to global state and use a logger instance to exfiltrate data, for instance.

If we could tell upfront that a third party function does not use global state, and also does not have untrusted code (both transitively), then we would know that it can only at most use the things that are passed to it, which is a much more tractable problem.
