### ISSUE TITLE
Determine IFC label for initial Application Node

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1213]
This is a follow-up from https://github.com/project-oak/oak/pull/1167#discussion_r442367599 (which still has most of the context, so it should probably be background reading for this issue).

TL;DR: The question is whether the initial Node of an Oak Application (i.e. the first WebAssembly node) should be labelled as "public trusted" or "public untrusted".

The main reason for "public trusted" is that it decides labels of subsequent nodes, therefore it needs to be trusted by the client sending in the data, and also it needs to be trusted in order to influence labels, which are themselves "public trusted".

The main reason for "public untrusted" is that an important assumption in Oak is that, even in the absence of trust (i.e. the client having to inspect the code of an Oak Application), Oak would provide some guarantees in terms of Information Flow Control.

**Comment by tiziano88** [comment]
Replying to this message by @aferr on https://github.com/project-oak/oak/pull/1167#discussion_r445446606:

> If node A has integrity X, then the code in A is trusted about X. If node B is creating node A, then B is really supplying the code in A. So B should also be trusted about X.

Intuitively, I would like to be able to express: A is trusted about nothing in particular; if it happens to create B with some particular code (e.g. aggregator, as determined by its hash) which is itself trusted (and checked by the trusted runtime), then B is allowed to be trusted about that (i.e. about being a legitimate aggregator).

**Comment by aferr** [comment]
Then in order to support what you described in any sound way, the integrity label of node B must also be "untrusted", and the confidentiality label of B must be one s.t. the confidentiality of A flows to the confidentiality of B. 

I think this proposal means you do not have integrity labels.

Also note that using NMIFC, "public_untrusted" is not capable of downgrading anything.

**Comment by tiziano88** [comment]
What if instead node B was created by another, this time fully trusted node? Could it have integrity of B in this case?

**Comment by tiziano88** [comment]
What I am trying to get to is that, perhaps there is a way to prove the soundness of this by saying that node A (untrusted) requests node R (for Runtime, fully trusted) to create node B. Because R both provides the code for B *and* sets its label, perhaps things are fine. At least, it makes intuitive sense to me, but I have definitely been wrong in the past :)

**Comment by conradgrobler** [comment]
I think there is a practical problem with this. As part of the node creation A must pass an initial channel handle to the runtime that is then passed to B. If A is untrusted it cannot create a channel with the integrity label of B. If the channel is untrusted, B cannot read from it, as it cannot read from a less trusted source. Even if the runtime also creates a channel with the appropriate label, A will not be able to write to it to send initialisation messages to B (or communicate with B at all). So there would need to be another preexisting node that is at least as trusted as B to be able to talk to B, and the question is then how will this node be created and configured.

**Comment by aferr** [comment]
The conventional rule is labelOf(creator) flowsTo labelOf(new_node). This checks both integrity and confidentiality. The integrity check says that the creator needs to be at least as trusted as the new node. Another way to put this is that integrity can either stay the same, or it can monotonically decrease. (Endorsements are a way around this, but they are meant to be the exception and should be well-justified). 

Because integrity can only monotonically decrease, it makes sense to start with a totally trusted node and then allow the application to "give up" privilege. So the initial node should be public and trusted. As a result, this initial node should just include ABI calls to create other channels and nodes. The code in this initial node would effectively contain the "low level policy" for the application. It should be inspected by participants in the application, and its contents should be included in the measurement for remote attestation. 

This code responsible for **initially** setting the integrity for the first few nodes really is a part of the TCB for all application participants and so its label should be trusted. Integrity is still decentralized though; a node with integrity label {A}, for example, can make new nodes that also have integrity label {A}.

> What if instead node B was created by another, this time fully trusted node? Could it have integrity of B in this case?

Yes, this is allowed. Note that many other things are allowed other than creating nodes with a fully trusted node. I'll use flume labels involving just integrity because these are simple to understand:

A node with trusted about both A and B can make a node trusted about just B:
Node X: {A, B} creates Node Y: {B}

A completely trusted node can create nodes that are each trusted about A and B. Those nodes can then each create new nodes trusted about A and B respectively:
Node X: trusted creates Node a1: {A}
Node Y: trusted creates Node b1: {B}
Node a1: {A} creates Node a2: {A}
Node b1: {A} creates Node b2: {A}

If the initial node is trusted, and the application can work by making all the application nodes untrusted (which is to say integrity labels are just not used because all nodes have the same label), then this can be simulated by having the initial node create all of these nodes.

>What I am trying to get to is that, perhaps there is a way to prove the soundness of this by saying that node A (untrusted) requests node R (for Runtime, fully trusted) to create node B. Because R both provides the code for B and sets its label, perhaps things are fine. At least, it makes intuitive sense to me, but I have definitely been wrong in the past :)

If R really is a node, then this also works with a setup where the initial node is trusted. Put the code running in R in the initial (trusted) node and have it create both A and B each with lower integrity labels (for example, {A} and {B} or {untrusted} and {untrusted}).

I suspect that "R" is not really a node though since it is called "runtime", but maybe I am missing some details about what you are doing. Is the code "in node R" really running in a node that is constrained by IFC, or is it something else that is "out of bounds"? 

As a side point:
>What I am trying to get to is that, perhaps there is a way to prove the soundness of this by saying that node A (untrusted) requests node R (for Runtime, fully trusted) to create node B. 

Presumably, this request is a message. Since this message is "untrusted" and since "R" is "trusted", receiving this message should require an endorsement. Did you encounter that?

**Comment by aferr** [comment]
Is "R" really a separate node, or is it a part of the runtime and kept out of bounds. If it is a part of the runtime, I suspect that there **is** a way to really pack it into a node and keep it within the bounds of IFC, which I think will be better. I can potentially help figure out how to do this if you think this makes sense, and if you want that.

**Comment by tiziano88** [comment]
If R were really a separate node, and fully trusted, we would still have to "manually" justify why it is trusted in the first place, right? So I am not sure whether it would be better to keep it as part of the runtime (so that perhaps its logic ends up being part of the coq model you are building), or whether to make it a regular node, and have a separate proof (perhaps an informal one?) that shows why anyone should trust this node about anything.

For instance, this node would do things like "given an arbitrary (untrusted) wasm module M and a confidentiality label C, create a node N that runs M, with confidentiality C and integrity M".

**Comment by tiziano88** [comment]
@aferr trying a different angle: if we went with your proposal of having the first node of an application being fully trusted by manual review, what would a reviewer check about it to decide whether to trust it or not? For instance, I'd imagine if the node did something like creating a node with a module M, but giving it integrity of a user, it would be a red flag, but in general what are the things that would have to be checked?

**Comment by tiziano88** [comment]
@aferr ping in case you missed my latest replies.

Also to reply directly to your idea of packaging this up as a "real" node: I think that may work; we would still need ABI calls for creating new node instances, and we would enforce that the label of the creator "flows to" the label of the newly created node, but we would create a "factory" node upfront which is fully trusted, and therefore whose integrity label trivially "flows to" any other label; this node would be created by the runtime to start with (so it does not really matter whether it is a real node or not, to my previous point, since the entirety of the runtime is already trusted anyways).

The question is still: if this is a separate trusted node, why should it be universally trusted? What are the criteria that someone would check on the implementation of this node, to decide whether they actually trust it?

**Comment by aferr** [comment]
Sorry. I did see this. Let's talk about this via GVC. I think it will be more productive.

**Comment by tiziano88** [comment]
Sounds good, thanks! Let's remember to update this conversation afterwards

**Comment by aferr** [comment]
okay sounds good :)  👍
