### ISSUE TITLE
de-duplicate `Message`, `Encodable`, `Decodable` types between Runtime and SDK

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1224]
Runtime `NodeMessage`:

https://github.com/project-oak/oak/blob/2cf69a76494d21189c171263679a9a4199866e29/oak/server/rust/oak_runtime/src/message.rs#L30-L39

SDK `Message`:

https://github.com/project-oak/oak/blob/2cf69a76494d21189c171263679a9a4199866e29/sdk/rust/oak/src/io/mod.rs#L46-L51

Runtime `Encodable`:

https://github.com/project-oak/oak/blob/2cf69a76494d21189c171263679a9a4199866e29/oak/server/rust/oak_runtime/src/io.rs#L42-L57

SDK `Encodable`:

https://github.com/project-oak/oak/blob/2cf69a76494d21189c171263679a9a4199866e29/sdk/rust/oak/src/io/encodable.rs#L19-L31

etc.

Note that this is currently blocked by #473, since otherwise this would introduce a dependency cycle.

Probably most of this will be solved at least partially by #1108.

**Comment by conradgrobler** [comment]
I dont think the runtime should depend on the SDK (or vice versa), so these should either be moved to the ABI (although it is not strictly part of the ABI) or a new shared crate that can be referenced by the SDK and the runtime.

**Comment by tiziano88** [comment]
I agree in principle, but I am not sure adding even more crates is actually a viable strategy. In practice even the split between ABI and SDK seems like a premature optimization (I don't expect anyone to actually depend on ABI but not SDK for the foreseeable future, until someone comes up with a completely different SDK on top of the same ABI).

So yes, for now I think moving them to the ABI makes sense.

**Comment by tiziano88** [comment]
@conradgrobler it sounds like we need to have a clear layering between crates, and decide what goes where (as a side note I believe @daviddrysdale has put some thought into this in the past already). We may consider adding a new intermediate crate between oak_abi and the SDK crate if it helps with anything, but could you detail how you suggest to go about it @conradgrobler ?

**Comment by conradgrobler** [comment]
#1324 will help with this. As discussed, we also need to remove the inconsistencies that are currenlty blocking the de-duplication:

- We should have a single `Handle` type: the suggestion is to standardise on the ABI handle
- We should use `OakError` consistently for the `Encodable` and `Decodable` traits
- We should change the `Sender` and `Receiver` structs to just contain the context (handle and type information) without any `send` or `receive` implementation. There should then be functions specific to the runtime and SDK for `send` and `receive` that take the `Sender` or `Receiver` instances as input parameters.
- We should move `HandleVisit` and all associated handle serialisation logic to the `oak_io` crate so that it can be used in the runtime as well.
