### ISSUE TITLE
Stop runner immediately after a failure

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1291]
Currently `runner` continues execution after some steps have failed. For example, it could continue working for 30 mins after `formatter` have shown an error: https://github.com/project-oak/oak/issues/1283#issuecomment-664954151

cc @anghelcovici @tiziano88 @rbehjati

**Comment by rbehjati** [comment]
I think that is intentional. So that you get a list of **all** the failing steps with a single CI-build, instead of having to trigger the ci-build again and again, to find out about all the failing steps. 

Stopping the `runner` immediately after the first failing step makes it almost pointless. In that case, I think it would be much better to have separate `cloudbuild` steps, like we had before, instead of having a single `runner_ci` step.

**Comment by ipetr0v** [comment]
Closing, since the behavior is intended.
