### ISSUE TITLE
Forbid declassifying reads and endorsing writes in IFC

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1301]
from https://project-oak.slack.com/archives/CHE9E13C3/p1595439459314800

Currently, a Node may use its full privilege for both reads and writes, but I suspect this leads to leaks (though I don't have a concrete example; @aferr suggested one [here](https://project-oak.slack.com/archives/CHE9E13C3/p1595440408318600?thread_ts=1595439459.314800&cid=CHE9E13C3)), or at the very least is unnecessary / inelegant.

I suggest we limit the privilege to allow:

- declassifying writes
- endorsing reads

and disallow the rest.

If / when we come up with a use case that actually requires using privilege in a different way, we can then perhaps start a discussion to re-add this functionality in a way that we feel does not cause leaks. The Coq model @aferr is developing should also allow us to model this behaviour and have a definite result of whether it is actually sound.

**Comment by conradgrobler** [comment]
Looking at this in more detail, I think that we should only allow downgrading (both declassification and endorsement) on writes rather than allowing declassification on writes and endorsement on reads. An endorsing read implies that the node endorses the data before it has seen it.

@tiziano88 WDYT?

**Comment by tiziano88** [comment]
Uhmm I am not sure, to me it still feels that a node should use its privilege when it decides to read from a less trusted input, rather than when it writes to a more trusted output.

**Comment by aferr** [comment]
If the goal is to be able to prove robust declassification it should be fine to allow downgrading of both kinds during both reads or writes. (Assuming also that privilege replaced with using integrity to control declassification and vice versa).

Separately from hyperproperties:
Even though an endorsing read means the node does the endorsement before it knows what the data does, it does at least mean that because a downgrading version of the read call is done instead of a non-downgrading one, that the trusted code is expecting untrusted data. So the code running in the trusted node could sanitize the untrusted data after it gets it. I think as long as long as downgrading reads are separated from normal ones, accidentally endorsing things should be limited.

I think it would be too limiting to prevent BOTH kinds of downgrades during reads, though maybe it is still possible to write useful applications if just declassification (but not endorsement) is allowed during reads. Where possible, I think its best to make these kinds of decisions based on security properties (which would mean allowing either kind of downgrade on either reads or writes).

**Comment by conradgrobler** [comment]
Should we then close this issue if implementing it will not improve any security properties?

**Comment by tiziano88** [comment]
I think actually if we had explicit declassifying operations this issue kind of disappear; for instance, a wasm aggregator node that uses its declassification privilege when reading would not be a good candidate for being trusted in a real aggregator application, but one that used its privilege when writing out would be fine. So I think #1670 covers it already. I still think in most cases we would not want to trust nodes that do declassifying reads, since it complicates reasoning about them, but we can deal with that separately.
