### ISSUE TITLE
Policy example: Evolving policies

### ISSUE THREAD

**Issue by seefeldb** [project-oak/oak#1411]
This is an example policy need, see #1410.

It explores changing policies for stored data, gaining a new way to declassify data.

This is similar to #1412, but simpler.

----

- a new policy says that data processed by `N` can be released to the public.
- there is already data saved that has been processed by `N`, prior to that new policy going into effect
- how can a node `M` that sends data to the public release previously processed data?

**Comment by seefeldb** [comment]
the issue is that then this example can be either
- node M which can only send public data out
- node M which can declassify data with integrity N

are equivalent in function, but picking either presupposes a solution (hence I want to avoid saying "N acquires declassification privilege", but instead describe the effect).

**Comment by aferr** [comment]
Here are some thoughts on how to solve this. I think with the current way we are thinking about policies, a policy consists of: 
 - the assignment of labels to locations (in this context: nodes, storage locations)
- what gets declassified
(Maybe in the future policies involve other things like propositions that we need to prove about nodes, or about data being sent, but for now I will stick more closely to what we are already doing)

I think the problem here is that at some point a concerned human (like a reviewer, or someone acting on behalf of users) agreed to a policy, and when the policy changes, it could be that the new policy does not comply with what the CH agreed to. If the new policy does not actually leak any more information than the old one, we don't need to bother the CH because they've effectively already agreed to the new policy. But if the new policy does leak more (or different) information, then we should inform them of the difference.

### Labels Changing at Runtime
Below are two answers that both involve changing labels after we have already started using the system. So first here is a bit of info on that. Most of the work on IFC does not allow labels to change at runtime. I have [related work](https://dl.acm.org/doi/pdf/10.1145/3061639.3062316) on this subject in the context of hardware, and with a simpler model of downgrading than NMIFC. The relevant bit is that when the label of a location X changes, as long as

` old(label_of(X)) ⊑ new(label_of (X))`

the change of the label does not leak any information because the new label is more restrictive than the old one. However if the above is not true, then the label change effectively does a downgrade from `old(label_of(x))` to `new(label_of(X))`.

In the hardware language, a programmer would need to explicitly add a downgrade expression that also specifies the new label in order to make this (downgrading) label change typecheck. I think in our context, this means we would need to notify the CH of the new downgrade (?).

There is also [this paper](https://ieeexplore.ieee.org/abstract/document/8049651) that mentions support for changing IFC labels at runtime in the abstract. I have not read it yet. I think the above intuition is probably true no matter what.

### Solution 1: Reduce the label of the stored data.

Old labeling:
Suppose the label of the storage location is initially Ln and the label of the node that does processing is Lm. Assuming it is not the case that Ln flowsTo Lm, then Ln can't be sent to Lm. 

New labeling:
In the new labeling, the label of M is still Lm, but the label of the stored data is changed to Ln', which presumably does flow to Lm. If Ln does not flow to Lm (so the data couldn't already be sent), there is a downgrade from Ln to Ln'. (A value of Ln' that always works is (Lm meet Ln) in case this is helpful). If Ln flowsTo Lm then there is not a downgrade.

### Solution 2: Give M more downgrading privilege.

I'll also assume that we're doing NMIFC style downgrading (though maybe a simpler downgrading model turns out to be better anyway).

Old labeling:
Again say the stored data has label Ln and initially M has label Lm.

New labeling:
The stored data keeps its old label Ln, but now we grant M more downgrading privilege. Just to split the labels into their parts, assume Ln = {Cn, In} and Lm = {Cm Im}. A new label for M that would work is Lm' = Lm join Ln = {Cn /\ Cm, In \/ Im }. This permits the desired chain of sends (from storage to M, from M to public) because:
- Ln flowsTo (Lm join Ln)
- Lm' can declassify from Lm' to public

The label change from Lm to Lm' is not itself a declassification because Lm does flowTo Lm'. However, by increasing the privilege of M, M can do a downgrade that it couldn't do before. So I think this means there is one more thing we would need to tell the CH, which is the change in permitted downgrades.

For an arbitrary label La={Ca, Ia}, the maximum label it can downgrade to public, trusted is just the "flip" of the label {Ia, Ca} (so we make the confidentiality the integrity and vice-versa). (This is a calculation I can type up if helpful). The change in maximum allowed downgrade is the meet of the old and new max downgradable labels. For the specific case of the change in label from Lm to Lm', this difference works out to be ((Lm join Ln) meet Lm) = Ln. This answer makes sense intuitively since "Ln" is also what we released with the other solution. 


### Solution 2.5
We could also consider not using NMIFC downgrading rules, and instead using a simpler downgrade model. Adding more downgrades to M would still be a solution in this case. Instead of using NMIFC downgrading rules, we could permit any downgrades, but require downgrades to be explicit in the code (for example, read and write calls that do downgrades would be distinct from normal read/write calls, and they would also include new label). Then this policy change would involve a new downgrading send that wasn't there before, and we would need to explain this new downgrade to the CH. The new label targeted by the send call would ostensibly have some intuitive meaning to the CH.

**Comment by seefeldb** [comment]
Why is the label of the data that has been process by `N`, i.e. what N emits and is then stored, `Ln = { Cn, In }`? I most Oak examples a node A wouldn't emit data with a confidentiality label Ca, but rather that of another downstream node that is a declassifier (and incoming data would already have that confidentiality label).

So why not `Ln = { P, In }`, where `P` reflects the previous policy, e.g. a node `P` that can declassify this data (and will continue to be able to do so)?

**Comment by aferr** [comment]
The above answers still work if the label of the stored data is the same as some node that is a successor of the processing node in the graph. You can think of `Ln` as just the variable name. Maybe making it `Ls` for stored is more clear.

Then we can say that the processing node has label `Ln`, the stored data has label `Ls`, and some node that declassifies the stored data has label `Ld`. (Note that the variable names are separated just for generality. It could be that Ls=Ld for example). For the needed sequence of sends to be permitted we'd need `Ln ⊑ Ls ⊑ Ld`. Otherwise, if you just take `Ln` and replace it with `Ls` two comments up, it should all still work just the same.

**Comment by seefeldb** [comment]
Thanks! But how do I now cover the "if it was processed by `N`" part of the new policy? I'd have to be sure that all data labeled `Ls` has been processed by `N` and will be in the future. That's possible by convention I suppose, but it would be great if we could use IFC to make these policy changes more robust.

For instance if the label of the stored data was `(Cp, In)`, then the policy change could be to change `Cp` to `Cp'` where `Cp' = Cp \/ (In /\ Im)`, meaning things with integrity N and M can declassify the data, assuming M endorses the data with this integrity (a la robust declassification). Or any other way to capture `In` as a requirement.

**Comment by aferr** [comment]
Does processing with N need to happen before the data gets stored or can it happen just after it's read from storage? If processing can happen after, we could give only the node doing N the ability to declassify the stored data. (Which I think is what your next paragraph implies we do).

If N needs to happen before storage, is it fine to just do N twice (once before storage, once after)? If doing N more than once is not fine, maybe an answer could be to run N on the data just before it gets stored, store a bit next to the data that says "yes this was processed by N", and some other node just after the data is read from storage can both check this bit and be necessary to do declassification.

The label for the stored data after the policy change (`Cp \/ (In /\ Im)' ) that you suggested makes sense to me. Since Cp' is lower in the lattice than Cp, this policy change would be a downgrade at the time of the change (which makes sense intuitively because now more things can declassify the data). Assuming the pipeline is now ?? -> storage -> N -> M, and N and M have labels {In /\ Im, In} and {Im, Im} respectively, the data can be sent directly to N without doing a declassify, then N can do a declassifying send to M.

(Sorry for the poor notational choice of using things like Cp, Ip as principals :) ).

**Comment by seefeldb** [comment]
The spirit of the problem statement is that `N` needs to run before storing and that it can't be rerun again. We might even want to assume that there is a mix of data in the store, some of which was processed by `N` and some of which wasn't.

I don't understand why whether something was processed by `N` needs an extra bit. Can't we capture that in the integrity part of the data (assuming storage retains labels)?

So you'd have `data(P, _|_) -> N(P, N)[endorses N on read] -> data(P, N) -> store -> data(P, N) -> M(P, M /\ N)[endorses M on read, declassifies P on write]`. So with the policy change `P` becomes `(M /\ N) \/ (...)`, which allows `M` to declassify it.

Alternatively this could be written as: `data(P, _|_) -> N(P, _|_)[endorses N on write] -> data(P, N) -> store -> data(P, N) -> M(P, N)[declassifies P]`. Where `P` becomes `M \/ (...)`, but we rely on `M` requiring `N` integrity.

(How `P` changes is another orthogonal question, let's tackle that separately)

**Comment by aferr** [comment]
Using integrity to represent that the data was processed by N makes sense to me as well.

The two sets of labels / pipelines you have also sound good to me. Just one tweak though:
I think ` N(P, _|_)[endorses N on write] ` needs to be something like `N(P /\ N, _|_) [endorses N on write]` if we use NMIFC rules since N would need to be able to read N-labeled secrets to be able to endorse up to N. (Though this is not needed if we drop the non-malleable endorsement part).

**Comment by seefeldb** [comment]
Great, thanks. Would the first version work (with endorse on read)? I like that one better because it's a bit more explicit in the new policy that the data had to be processed by `N` (vs assuming `M` does on its own require that). Not a big difference though.

**Comment by aferr** [comment]
Yes the first version does work. (Though there is a downgrade during the policy change itself since the label of the stored data is is moving down in the lattice).
