### ISSUE TITLE
Policy example: Aggregation (aggregator's perspective)

### ISSUE THREAD

**Issue by seefeldb** [project-oak/oak#1414]
This is an example policy need, see #1410.

It's a complement to #1413, which covers the user's perspective.

---

Both policies will be active at the same time. #1413 describes how a user releases data to `example.com`. But how can `example.com` make sure that they are only receiving data from genuine users without also learning something about those users?

Can `example.com` express a policy about the data it receives, e.g. that it was processed by `Aggregator` and that all contributing users were verified to be genuine.

In this example, there might be a gating node `Deduper` before `Aggregator` that makes sure no user can submit data twice. Note that this wouldn't have to appear in the user's policy, just in the aggregator's policy. In fact ideally `Aggregator` can be used without modification with different `Deduper`s or other pre-processing, as that's the component that the user needs to trust and is hence ideally widely reusable.

**Comment by tiziano88** [comment]
Thanks for writing this up Berni. 

I think anything along these lines may end up being captured as an integrity label, in particular, each aggregator implementation may have extra logic to prevent duplicates, or check the integrity of the incoming data, etc. Since a particular aggregator may trivially endorse its own output with an integrity label corresponding to its own code (for instance, via a Wasm hash label), then I think as long as Oak propagates this over gRPC, then the receiver (e.g. example.com) may decide what to do with it (e.g. only accept data with integrity of aggregator modules that are known to do strict checks on incoming data).

Is this roughly aligned to what you are thinking?

**Comment by seefeldb** [comment]
I think there a couple ways to do this, from least reliant on the policy mechanism to most:
 - Use gRPC auth in some way so the receiver knows it can from this particular Oak application that they wrote and started. Since they know what's going on, they can reason about it directly. Works, but relies on tight coupling.
 - `Aggregator` integrity implies that `Deduper` ran before, because `Aggregator` checks that + as you say, that integrity is propagated over gRPC. Much better, but now `Aggregator` is specific to `Deduper` (or includes the code) and also appears in the user's policy. Ideally `Aggregator` is independently verifiable and highly reusable in other contexts, while `Deduper` is more specific to this scenario (and only needs to be trusted by the receiver).
 - The `Deduper` integrity label is propagated through `Aggregator` in a way that `Aggregator` doesn't need to be modified for (i.e. it'll also work with a future `Deduplinator`), and the receiver expects both in the integrity label. This would make `Aggregator` highly reusable, but it's not 100% clear to me what the conditions are for the propagation of `Deduper`.
 - Maximizing reuse: Maybe `Deduper` -> `Preprocessor` -> `Aggregator` could be possible, with `Aggregator` most reusable (i.e. independent of the others), `Deduper` still somewhat reusable and `Preprocessor` very specific to the use-case (and could be multiple nodes).
