### ISSUE TITLE
Add a comprehensive example using HTTP server node

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1433]
We need an interactive http example, something similar to aggregator, with the possibility to access it from a browser.
The following should be supported/needs to be done:
 - HTTP POST to submit data (for now it could be just a number)
 - HTTP GET to show the aggregated value 
 - JavaScript client 
   - Sets headers as labels 
- Deploy the serve on GCP
- With CA-signed TLS certificate 
- Serve on a new subdomain of oakexamples.dev

**Comment by tiziano88** [comment]
I think this may be the Private Information Retrieval / Trusted Database example (https://github.com/project-oak/oak/pull/1423).

We could add a simple web client that relies on the [Oak Chrome extension](https://github.com/project-oak/oak/issues/1492) to enter Oak private mode, and then ask the user for their location (or use some geolocation web API to determine it).

The back-end would be changed to accept HTTP requests instead of / in addition to gRPC.

cc @ipetr0v @juliettepretot

**Comment by tiziano88** [comment]
> > The back-end would be changed to accept HTTP requests instead of / in addition to gRPC.
> 
> Will it require creating two separate `Main` Oak Nodes? Since `run_event_loop` accepts a single handle?

I was thinking either two distinct applications, one gRPC and one HTTP, or some parameter (perhaps passed via the config map) that allows selecting which version to run.
