### ISSUE TITLE
Encapsulate node + channel creation in SDK function

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1583]
The pattern of creating a channel and node with the same label, and then closing the read handle of the channel, is quite common throughout Oak applications, we should probably think of a better abstraction for it in the SDK.

e.g.:

https://github.com/project-oak/oak/blob/22bbbbb885874bc02a0688758b8fb43782776b3f/examples/chat/module/rust/src/lib.rs#L57-L60

_Originally posted by @daviddrysdale in https://github.com/project-oak/oak/pull/1582#discussion_r504433825_

**Comment by ipetr0v** [comment]
Are we planning to only use a single incoming channel per node?

Is so, we probably can do something simple, like:
```rust
struct Node<T> {
    sender: Sender<T>,
}

impl<T: Encodable + Decodable> Node<T> {
    pub fn send(data: &T) { ... }
}
```

**Comment by ipetr0v** [comment]
@tiziano88 what do you think about the following `NodeBuilder` abstraction: https://github.com/project-oak/oak/pull/1618?
I think in the future we can move towards creating all Oak nodes using builder.

**Comment by ipetr0v** [comment]
Also we probably want to have separate `struct` for each node type: i.e. `struct WasmNode`, `struct GrpcServerNode`, etc. Because it's much easier to think about nodes in terms of objects.

The only problem with such approach is that we need to support multiple node communication behaviors:
- Nodes that only listen to incoming requests: `GrpcClientNode`
- Nodes that only send data back: `GrpcServerNode`
- Nodes that both listen and send data back: ones that use the same channel to listen and to send responses back

And we need to make it obvious that these nodes communicate this way.

**Comment by ipetr0v** [comment]
Closing because of https://github.com/project-oak/oak/pull/1658
