### ISSUE TITLE
in-memory storage node

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1606]
In many applications it is common to have some state, which gets accessed (read and written) by nodes with specific labels.

For instance:

- in the chat application, there is per-label state which represents a chat room (e.g. previous messages), which participants to that room both read and write
- in the trusted database application, there is a global public database, and per-label nodes are spawned in order to retrieve one or more entries from it

Currently, these applications are modelled in a router / worker pattern, in which a public router node creates per-label worker nodes, and routes requests to them.

In the chat example, each worker node contains its own state internally, which starts off as empty, and it can freely access it, so there is not much movement of data from the router node into the worker nodes.

In the trusted database example, the database is effectively owned by the router node itself, which sends it in its entirety to each worker node at each request; this is not particularly efficient, since it results in a copy of the database being created for each invocation, which means it is copied at least three times: in the router node, in the channel, and then again in the target worker node Wasm memory (plus additional overhead for actual serialization / deserialization).

In principle, if we had a more precise IFC (perhaps at the language level), we may implement this pattern more efficiently with a Wasm node that stores data internally, for instance in a hashmap; when this node receives a "get" request, the system would know that this does not mutate the data store or leave any trace behind about the element that is being looked up; effectively, if the node state is read only (and there is no other state derived from the request that gets persisted), then the node may have a public label but at the same time be allowed to receive messages from nodes with more confidential labels, without having to duplicate itself for each of them. This is because it can be shown that it does not "learn" anything about any incoming request.

In practice, this may be implemented either by a generic copy-on-write / checkpoint / restore mechanism (e.g. restore the Wasm memory after each received message), or, by manual inspection of the code, which in our case may be implemented natively as part of the Oak Runtime, and allowed to declassify arbitrary data when reading from non-public channels (i.e. it would always have a very high declassification privilege).

@aferr @project-oak/core

**Comment by tiziano88** [comment]
If we implemented this as a new native pseudo-node, what label should it have?

Assuming for a moment that the contents of the database are public, and we are just trying to protect the confidentiality of lookup requests coming from non-public worker nodes, these worker nodes need to be able to send these requests without performing a declassification; therefore it seems to ma that the confidentiality label of the channel to the storage node must be Top (or at least, an upper bound to all the labels of any node that wants to send requests to it).

Then the storage node may be configured in either of these ways:

- Top confidentiality label and max declassification privilege; in this case it will do a normal read when reading a request from the incoming channel and a **declassifying write** when replying to the request
- Public confidentiality label and max declassification privilege; in this case it will do a **declassifying read** when reading a request from the incoming channel and a normal write when replying to the request

@aferr does this make sense? which one is preferable? are there other (better) alternatives?

**Comment by ipetr0v** [comment]
> we may implement this pattern more efficiently with a Wasm node that stores data internally

Should it be a Wasm node or a pseudo-node? I think having it as a pseudo-node will allow us not to make exceptions in IFC (i.e. exceptional Wasm nodes) and just have it as a part of Oak Runtime.

**Comment by ipetr0v** [comment]
> Top confidentiality label and max declassification privilege

If such nodes exist, does it mean that anyone can create node with similar labels, and then read all protected data and declassify it outside of Oak?

**Comment by juliettepretot** [comment]
> Assuming for a moment that the contents of the database are public [...]
>
> Then the storage node may be configured in either of these ways:
> 
> * Top confidentiality label and max declassification privilege; in this case it will do a normal read when reading a request from the incoming channel and a **declassifying write** when replying to the request
> * Public confidentiality label and max declassification privilege; in this case it will do a **declassifying read** when reading a request from the incoming channel and a normal write when replying to the request

@tiziano88 Purely based on what feels more intuitive, I'd say option 2 is better. It feels counterintuitive to label public data as top confidential, when the intention isn't to protect that data.

**Comment by juliettepretot** [comment]
I'm also curious why this needs to be specifically in-memory. It seems to me like this is simply around having a better mechanism for common data, regardless of how that data is stored.

**Comment by tiziano88** [comment]
> > Top confidentiality label and max declassification privilege
> 
> If such nodes exist, does it mean that anyone can create a node with similar labels, and then read all protected data and declassify it outside of Oak?

I don't understand the attack you are suggesting, could you clarify? Note that I am assuming the data in the storage node is public (for now).

**Comment by ipetr0v** [comment]
> I don't understand the attack you are suggesting, could you clarify? Note that I am assuming the data in the storage node is public (for now).

Maybe I just didn't understand it correctly.
What I was thinking is that, if a node has a top-secret label (which is above all labels in the lattice) - it can read and declassify everything. If so, who stops application developers from adding such a label to their nodes and reading/declassifying all the data?

**Comment by tiziano88** [comment]
BTW, not sure whether this was what you were suggesting, but there may be a potential attack if we use the "invocation" pattern to interact with this node:

- node_0 creates an invocation message which contains a request receiver and a response sender, both labelled with node_0 confidentialiy; this is intended to be sent to the storage node in order to retrieve an element identified by the request
- node_1 somehow gets hold of this invocation message; it cannot read the request directly (since its own label does not allow it), but it may create another invocation by using the request from node_0, but a response sender with node_1 label, then sends this invocation to the storage node, and it receives back the value corresponding to node_0 request

**Comment by tiziano88** [comment]
> > I don't understand the attack you are suggesting, could you clarify? Note that I am assuming the data in the storage node is public (for now).
> 
> Maybe I just didn't understand it correctly.
> What I was thinking is that, if a node has a top-secret label (which is above all labels in the lattice) - it can read and declassify everything. If so, who stops application developers from adding such a label to their nodes and reading/declassifying all the data?

Is your point that allowing top-secret labels in general would cause leaks? Why would a random node with top secret label be able to declassify everything?

**Comment by tiziano88** [comment]
> I'm also curious why this needs to be specifically in-memory. It seems to me like this is simply around having a better mechanism for common data, regardless of how that data is stored.

If data were stored outside of the control of the oak_runtime, then it becomes observable by external actors, and therefore confidentiality guarantees cannot be upheld. We should start with in-memory, and carefully consider whether the pattern can be expanded to persistent storage outside of the oak runtime (e.g. by leveraging encryption primitives before storing the data persistently, which I believe @daviddrysdale has been thinking about)

**Comment by ipetr0v** [comment]
> Is your point that allowing top-secret labels in general would cause leaks? Why would a random node with top secret label be able to declassify everything?

IIUC node with a label `L` can declassify all labels `m` that flow into `L`. And if top-secret `T` is above all labels, then it can declassify everything, correct?

**Comment by tiziano88** [comment]
> > Is your point that allowing top-secret labels in general would cause leaks? Why would a random node with top secret label be able to declassify everything?
> 
> IIUC node with a label `L` can declassify all labels `m` that flow into `L`. And if top-secret `T` is above all labels (all labels flow into it), then it can declassify everything, correct?

The confidentiality label of a node does not determine what it can declassify. The declassification privilege is what allows declassification. Otherwise any application in which a worker node for a specific label operates on labelled data would be able to declassify such data, which would be pretty bad, right?

**Comment by ipetr0v** [comment]
So it's not possible to just assign `T` as a declassification label?

But data-store node still has such a label:
> Top confidentiality label and max declassification privilege

**Comment by tiziano88** [comment]
> So it's not possible to just assign `T` as a declassification label?

No sure what you mean by "declassification label"; currently

- the **confidentiality label** is assigned by the creator node
- the **declassification privilege** is [assigned by the Oak Runtime itself](https://github.com/project-oak/oak/blob/03c3b965bb8813051dbe897f38c0e84f1b5aaa4b/oak_runtime/src/node/wasm/mod.rs#L996-L1024)

**Comment by ipetr0v** [comment]
Based on what `declassification privilege` is assigned?

**Comment by tiziano88** [comment]
> Based on what `declassification privilege` is assigned?

Based on the link I posted earlier -- e.g. for a wasm node: https://github.com/project-oak/oak/blob/03c3b965bb8813051dbe897f38c0e84f1b5aaa4b/oak_runtime/src/node/wasm/mod.rs#L996-L1024

**Comment by aferr** [comment]
@tiziano88 

I don't think this should be a feature of the core runtime because it can be emulated with the ABI as-is. I think this is useful to have as either: a thin wrapper around the existing ABI, or as a "design pattern".

I don't like the idea of adding adding nodes that act as exceptions to IFC. The only exceptions to IFC should be the downgrading ABI calls. I don't think we need to bake in other exceptions to support in-memory storage.

I think persistent storage is a feature worth considering building into the core oak runtime, though.

To implement this with the ABI as-is, storage locations can be implemented as channels. The storage node has the handles to the channels, but is public.

**Comment by juliettepretot** [comment]
@aferr Would this approach work with storage nodes that are not fully public? Eg ones that have the purpose of keeping a common state for subset of nodes that are all above a given confidentiality bar?

**Comment by aferr** [comment]
@juliettepretot 

The idea is that the storage node has handles to channels, so it can move them around but it can't read from the channels (because public is not "over the bar"). 

With this approach, for a node with label L to make a request to the storage node, it would need to declassify "the fact that it is making some request", but it does not declassify the data itself. 

So this is a way for a public node to keep non-public data (that it can't read or write).

**Comment by tiziano88** [comment]
> To implement this with the ABI as-is, storage locations can be implemented as channels. The storage node has the handles to the channels, but is public.

How would a Node with non-public label L request to look up one of the storage locations from the public storage node, without declassifying its query?

**Comment by aferr** [comment]
> How would a Node with non-public label L request to look up one of the storage locations from the public storage node, without declassifying its query?

Ah ok I didn't realize queries needed to be secrets, but I see your second post now. The thing I was suggesting is similar to the second option you proposed.

I'm not convinced we have any answers that hide the queries. In both the options you listed there is a declassification either when the storage node does a read or it does a write. I think either way what gets declassified includes the query:
- if the store has top confidentiality, what value it needs to declassify depends on what was queried
- if the store is public, the query is declassified when the query is sent (it doesn't really matter if this is in the storage node or the node making the query)
, so the information leak was just moved around rather than prevented.

(I would tweak your second option slightly: make the storage node {public, untrusted} and have the querying nodes declassify their query to t he store. Since this declassification _does_ happen, I'd rather have the bit of code thats giving up the info be responsible for deciding to give it up. The querying nodes also do the endorsing in this case).

I think you can give a lower bound on the level to which this information is downgraded, but we still wind up in a situation that does not seem useful to me.  It's the meet over all the labels in the database, which means its public to all the users of the database. (I think you can get the same lower bound with any of the options discussed in this thread). Maybe this does turn out to be useful in the chat app: if there is one store per room, then all the participants in the room learn about queries to the room, but people that are not at all related to the room learn nothing about the queries.

Popping up a level, why do we care about stopping this particular side channel when other side channels are out of scope? Is there some value in looking at applications that have already been written for IFC elsewhere like in Aeoulus's code release (or others), and trying to just port them to Oak?
