### ISSUE TITLE
Fix runtime tests

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1671]
The change in #1619 has caused the runtime tests to fail; although the tests do not actually fail!

This is because `node_stop` is now called when `proxy.stop` is called. Previously it was called before stopping the runtime:

https://github.com/rbehjati/oak/blob/caa91c86f4f2b9d451d7a8bae9b56d82375f4b3e/oak_runtime/src/tests.rs#L86-L100

**Comment by rbehjati** [comment]
I can think of the following fixes:
- Add a small delay, using `std::thread::sleep`, before stopping the runtime. This might make the tests brittle.
- Add a new `stop_node` method to the Runtime. We could limit it to be used only for testing. This method would require a `node_id` as an input. To be able to implement this, I think `node_register` should return the `node_id`.
- Revert this part of the change.

@tiziano88 WDYT is the best solution here?

**Comment by daviddrysdale** [comment]
Yeah, the `oak_runtime` unit tests are in a bit of a state &ndash; half a dozen of them are failing, but the failures are lost along the way.

It's generally better to use a synchronization primitive to sync between threads, rather than "synchronize-via-sleep" &ndash; #1720 uses a condition variable.

**Comment by rbehjati** [comment]
I agree. I still need to learn about these things in Rust. `std::sync::mpsc` looks interesting.
