### ISSUE TITLE
Appropriate label for the aggregator example blocks gRPC responses back to the client.

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1674]
The aggregator handler node should have a label that contains both a `WebAssemblyModuleTag` and `TlsEndpointTag`. The node has the privilege to declassify the `WebAssemblyModuleTag`, but not the `TlsEndpointTag`. This is Ok for using the gRPC client pseudo node to report the aggregate results to the external service, as it would have the privilege to declassify this.

The problem is that the aggregator handler node cannot write to the response channel on the gRPC server invocation to let the client know that the data submission was successful, as it has a "public" label.

**Comment by tiziano88** [comment]
**I think** (but I am not 100% sure) this is WAI.

Any response that is sent back to the client must be based on public information, or information that can be declassified directly back to the client. In particular, it should not depend on data labelled for a TLS endpoint, since that data is really only declassifiable to that TLS endpoint, no matter whether it originally came from the client. I guess in this case a disjunction label would help, but it seems too much of a loosening compared to really labelling to the TLS endpoint. I think @ipetr0v also suggested using disjunction labels for this case.

**Comment by conradgrobler** [comment]
It is WAI in terms of IFC, but it means that we cannot currently implement the appropriate labels. If we implement it, the success response can not be sent back to the client and the client just keeps waiting. We need to think of a way to implement a "fire and forget" type message from the client so that it does not depend on the server responding to continue.

**Comment by tiziano88** [comment]
I think the chat example has a similar (though simpler) pattern: 

https://github.com/project-oak/oak/blob/2fbd54a89589385ec007a1011b68a49112eabdd5/examples/chat/module/rust/src/lib.rs#L96-L127

It sends a message back to the caller from a node (in that case the router node) that has not seen the request data. Not sure how well this maps to the aggregator example though, I think @ipetr0v started doing a similar refactoring for the aggregator, maybe that helps.

**Comment by conradgrobler** [comment]
Something similar can be done, but it would mean that the aggregator handler node would need to be reimplemented as it cannot use the SDK-generated gRPC handling code (which would try to also send back a response over the response channel).
