### ISSUE TITLE
We cannot currently declassify `top` labels except by using `top` privilege.

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1704]
Seeing that we don't support negation of tags, the current implementation of declassification is slightly inaccurate. As an example: suppose we have a `node_privilege` that allows some declassification but is not top privilge, then the following is currently true `node_privilege.downgrade_label(confidentiality_label(top()) == confidentiality_label(top())`.

This probably does not have any impact on realistic usage scenarios, but is mathematically incorrect.

**Comment by tiziano88** [comment]
Why would you expect a non-top privilege to be able to declassify a top label? Or did I misunderstand?

**Comment by conradgrobler** [comment]
It should be able to partially declassify. In the case where we have the per-`sub_lattice_top`s, it might start being an issue. If we sequentially downgrade the `global_top` confidentiality label using each `sub_lattice_top` in turn, we will still end up with `global_top` at the end.

**Comment by tiziano88** [comment]
I don't think it should be able to partially declassify. If something is top secret, only the top privilege can declassify it to public. Any other privilege leaves it completely classified. But I may still be missing something, I didn't get what you are suggesting it should declassify to.

**Comment by conradgrobler** [comment]
Let's say we only have two sub-latices: `users` and `code`, each with a `top` element. Then `global_top` = `user_top` ∧ `code_top`.

If we downgrade a label with `global_top` confidentiality using `user_top` privilege we should end up with `code_top`.

**Comment by tiziano88** [comment]
> Let's say we only have two sub-latices: `users` and `code`, each with a `top` element. Then `global_top` = `user_top` ∧ `code_top`.

This is not quite correct. There are two lattices: one is the "atomic principals" lattice (with its own sub-lattices), i.e. the hierarchy of how individual principals relate to each other; in this lattice there are no logic connectives, but there are still "meet" and "join" operations on the lattice (let's use ⊓ and ⊔ for this). Then the label lattice is induced from the atomic principal lattice by means of conjunctions and disjunctions, which has the effect of producing a "larger" lattice with all the combinations of atomic principals under logic connectives. In this lattice there may be logic connectives (∧ and ∨) within elements of the lattice, but those are not the overall lattice joins and meet.

In the label lattice, `a ⊓ b == a ∧ b`, because `a ∧ b` is an element of this lattice, which is their least upper bound. But in the atomic principal lattice, `a ⊓ b == ⊤`, i.e. there is nothing above a and b apart from top.

**Comment by conradgrobler** [comment]
I am not clear on the implication of this. In the case where `a ⊓ b == ⊤` what is the result when `a ⊓ b` is downgraded using privilege of `a`?

**Comment by tiziano88** [comment]
> I am not clear on the implication of this. In the case where `a ⊓ b == ⊤` what is the result when `a ⊓ b` is downgraded using privilege of `a`?

The result of declassifying ⊤ with anything other than ⊤ is still ⊤.

**Comment by conradgrobler** [comment]
I see.

Does the same apply to the the top of each of the sub-lattices in the label lattice (e.g. if user-top is declassified by a single user is the result still user-top)?

**Comment by tiziano88** [comment]
> I see.
> 
> Does the same apply to the the top of each of the sub-lattices in the label lattice (e.g. if user-top is declassified by a single user is the result still user-top)?

Correct, which makes sense intuitively. Only the actual overall gRPC pseudo-node implementation has the ability to declassify arbitrary users. Assuming that spawns per-user nodes, each of them would have only the per-user declassification privilege, but not the overall one.

**Comment by conradgrobler** [comment]
It does not make intuitive sense to me :) but will close this anyway seeing that the current implementation is correct..
