### ISSUE TITLE
Merge two levels of ABI abstraction in SDK

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1735]
Currently we have pairs of similarly called functions in SDK that correspond to ABI calls.
For example, we have a low-level `node_create`:
https://github.com/project-oak/oak/blob/ee74b9d33f25c16fc080604c5bb0867674d233cf/sdk/rust/oak/src/lib.rs#L270-L275

we also have a high-level `node_create`:
https://github.com/project-oak/oak/blob/ee74b9d33f25c16fc080604c5bb0867674d233cf/sdk/rust/oak/src/io/mod.rs#L41-L45

and both of them correspond to another `node_create` which is an ABI call:
https://github.com/project-oak/oak/blob/ee74b9d33f25c16fc080604c5bb0867674d233cf/oak_abi/src/lib.rs#L239-L247

I think it makes sense to merge high-level and low-level versions.
Or maybe it's better at least to make low-level versions `pub(crate)`, and move high-level versions from `oak::io` to just `oak`.

The only problem with it - is that `abitest` currently uses the low-level version of SDK functions.

cc @tiziano88

**Comment by tiziano88** [comment]
I wonder whether we should perhaps make `abitest` use the actual calls from `oak_abi` (though that may be too low level), or just use the more type safe versions (currently the ones from `oak::io`, perhaps moved down one level). I don't think there is much value in keeping the intermediate versions around, except perhaps as `pub(crate)` as @ipetr0v suggested. But I haven't looked closely at `abitest` to judge whether it makes sense to move to the higher-level helper functions entirely. Note that the high-level functions do not have much more logic associated with them, it is mostly about type safety and creating nodes and channels together rather than separately, so I think it would be acceptable to use them in `abitest`. @daviddrysdale WDYT?
