### ISSUE TITLE
HTTP-pseudo-node: Allow Oak Applications to customize handling of unlabeled requests

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#1875]
Currently the Oak Runtime rejects unlabeled HTTP requests and renders a a hardcoded error page. https://github.com/project-oak/oak/blob/3deab43be26dff143a5f61ca0ab8ab21b7a94e93/oak_runtime/src/node/http/server.rs#L322

It would be useful for oak applications to customize this behavior. They might choose to render their own error page, or crucially they might want to choose to treat unlabeled requests as equivalent to requests labeled as `publicuntrusted`. It's arguably a requirement for serving browser clients from the Oak Runtime, as (excluding the use of extensions) the initial request to load the client cannot realistically have a HTTP label header already.

cc @rbehjati @tiziano88 @conradgrobler for thoughts/opinionz

**Comment by rbehjati** [comment]
How dangerous is it to treat no label as `public_untrusted`?
Or perhaps, we could use the user's identity as the request-label, if a singed-challenge is provided in the request.

**Comment by juliettepretot** [comment]
@rbehjati 
> How dangerous is it to treat no label as public_untrusted?
I don't personally see a danger, since it's the lowest level label. While I suppose an attacker could remove the label header from a user's request, thereby declassify the data, they could also overwrite the label header so it doesn't make a real difference. Worth keeping in mind too that Oak applications would need to opt into this, the default behaviour would remain unchanged. 

> Or perhaps, we could use the user's identity as the request-label, if a singed-challenge is provided in the request.
Using the identity instead unfortunately won't help much, as it presents the same problem as the label requirement for _all_ requests (including the initial request).

**Comment by rbehjati** [comment]
What is the benefit of having the browser directly interact with an Oak application? I thought, we always needed a special Oak client (either RUST, JS, or CPP).

**Comment by juliettepretot** [comment]
The Oak Runtime could serve the JS client.

The flow would look like so:
1. A user loads an HTTPS endpoint provided by the Oak Runtime using the browser
2. the Oak Runtime responds with a JS client
3. the user's browser parses and executes the JS client
4. From now on, all interaction is performed from the JS client to/from the Oak Runtime

I think this is useful. The http_server example already uses browser <-> runtime interaction but relies in a 3rd party extension to set labels. 
https://github.com/project-oak/oak/main/examples/http_server/README.md#L30

**Comment by rbehjati** [comment]
What is the benefit of using Oak for serving the JS client? Everything is public about the JS client, so a simpler non-Oak web application can just load and use it. Is not that right? 
I think in the `http_server` example we are using ModHeader just to keep things simple, also because we don't currently have a JS client, IIUC.

**Comment by juliettepretot** [comment]
Yup, you're correct that the web client could be served from a different host. I think there's two advantages two serving it from the runtime itself:

- In many cases, we can assume that users have established trust to the identity of the Oak Application, beyond attesting the Oak runtime. Hence it seems sensible to not ask them to trust a separate URL in order to download a client. Obtaining the correct client is vital, as it could conceivably be uses to leak user info. 
- It makes our examples a lot easier. Installing the ModHeader extension adds a lot of complexity, esp since we advise the use of a seperate chrome profile for safety.

But yeah, not 100% needed. :)

**Comment by rbehjati** [comment]
Sounds good to me :)
