### ISSUE TITLE
Use exported key material from TLS for public key auth

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1898]
I think we should be able to use https://docs.rs/rustls/0.19.0/rustls/trait.Session.html#tymethod.export_keying_material to generate some key material to use for challenge-response auth, instead of inventing our own protocol, but I have not looked into it yet.

cc @rbehjati

**Comment by rbehjati** [comment]
What exactly is the content of the keying material (I could not find much useful information after a quick look)?
But IIUC, keying material is generated per session. However, for authentication we need a more permanent public key that exists beyond the session. For example in the chat example, multiple clients must have access to the same key-pair. More generally, at the moment, I don't see much use in labelling anything with a public key that is only valid for an ephemeral session. Maybe I am missing something.

**Comment by conradgrobler** [comment]
A few points:

- I believe the key material is just some bytes that are computationally indistinguishable from random (unless you know the session key).
- Ephemeral sessions would be useful for the Trusted Information Retrieval example, so that the label does not have any persistent link to a user's identity.
- I don't think this feature is a good match for ephemeral keys. Ephemeral keys can just be random, as only the client needs to know the private key. This feature is inteded to support https://tools.ietf.org/html/rfc5705 where the client and the server want to use the TLS session key as the basis to derive additional shared key material for use in other communications in higher-level protocols.

**Comment by tiziano88** [comment]
I was just suggesting using the key material as challenge, not as key. It would allow client and server to agree on a challenge that is also bound to the actual TLS session. The client would still need to sign it in the usual way.

This would simplify things if we decide to do something similar for remote attestation, which would also be bound to some exported key material from the specific TLS session in context.

cc @ipetr0v

**Comment by conradgrobler** [comment]
Ah, ok. The client and the server being able to agree on a chalenge without actually sending the challenge to the client as a separate call seems like a good idea.

I don't think this would be simple to implement.

On the Rust side Tonic does not seem to provide a mechanism to access the underlying TLS session. This would probably require moving away from Tonic and doing client and server gRPC implemenations on top of raw Hyper. For the server it might not be such a big job (as it will look very similar to the HTTP server node), but will be quite inconvenient to reimplement on the client side.

I also could not see any obvious API in any of the other gRPC client libraries (e.g. c++, java, etc) to get access to a TLS session to be able to export keying material from the connection.
