### ISSUE TITLE
Selective logging for Oak Functions Loader

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1955]
Currently we have a way of enabling or disabling logging completely via a feature:

https://github.com/project-oak/oak/blob/46cf7e38d998c60ae4c1b1d65e929951deefa2c6/oak_functions/loader/src/main.rs#L51-L55

This is not great because when disabled, there is no way to log anything at all, even if we would consider it safe (e.g. incoming request size, etc.).

We should think of some better way of handling this, in a way that does not allow third party dependencies to accidentally log sensitive data along the way (e.g. by setting `RUST_LOG=trace`).

**Comment by tiziano88** [comment]
@project-oak/core

**Comment by tiziano88** [comment]
One way would be to stop relying on logging as an ambient authority, and instead transforming into a capability. For instance we could define our own `Logger` struct, and pass a reference to it to the functions that we expect to log -- in particular, this would not be passed to third party deps, so they would never be able to log, as long as we do not initialize the ambient logger.

**Comment by tiziano88** [comment]
Note that there would still be no guarantee that third party code does not log in some other way (e.g. just by `println!` or writing to a file or whatever else). Unfortunately Rust does not have a native distinction effect-free and effectful functions.

Perhaps @alastairreid @fshaked have any ideas?

**Comment by tiziano88** [comment]
Maybe relevant: https://github.com/bytecodealliance/cap-std (though probably not directly useful)

**Comment by alastairreid** [comment]
A few thoughts:

- it appears that it is relatively easy to write new "lint" passes because the Rust compiler is structured as a library and allows you to add plugins that will be applied to various parts of the code at different phases. See [plugin chapter](https://doc.rust-lang.org/nightly/unstable-book/language-features/plugin.html) of the Rust unstable book.
- of course, deeper analyses would be more work - but the important thing here is that the plugin architecture gives access to the AST, the type system, macros before/after expansion, #[annotations], and all the code present in the compiler for manipulating the AST, etc. So the effort is just the unavoidable effort of designing an analysis, handling all the different different AST nodes in a real language, etc.
- You'd want to be clear up front which Rust crates you want to "just work" or to work with limited modification so that analyses can be designed to handle that code.
  - eg are there any language features that it would be necessary and acceptable to ban or restrict?
  - eg what about crates that use unsafe to work round borrowing limitations, foreign function calls, LLVM intrinsics, etc.?
  - This is likely the hard part of the task - there is likely to be a long list of hard choices/compromises that depend a lot on how narrowly/broadly you need the resulting tool and modified libraries to be usable.

**Comment by tiziano88** [comment]
@conradgrobler if you are looking into this, could you try with experimenting with https://docs.rs/log/0.4.14/log/#compile-time-filters ? I am not sure whether it is enough to specify those flags in the top-level crate in order for them to propagate down to third party crates. It would be nice to double check whether a statement like `log::warn!("test-warn")` ends up in the resulting compiled binary with and without the `max_level_off` / `release_max_level_off` feature, for instance.

**Comment by tiziano88** [comment]
if this turn out to be working, I would also suggest we have some sort of test to verify that log statements are completely removed at compile time. e.g. we could have something like `log:error!("test-log-statement")`, and then grep for that string in the compiled binary and verify that it is not there (and verify that it is there otherwise, of course).

**Comment by conradgrobler** [comment]
I did some experiments, and it does not seem to inherit the features. I tried the `max_level_off` and `max_level_debug` features for the reference to the `log` crate on the Oak functions loader. The `want` crate is referenced indirectly by hyper and tokio and has two trace logging lines in `poll_want` (https://github.com/seanmonstar/want/blob/13093a962ac4ea1a623c08f4ac726842cd422980/src/lib.rs#L195)

I built the output with the different features and compared the disassembly for this function with the original. It did not change at all. I also checked the rest of the disassembly for this crate. There were minor differences such as reordering of some sections, but it did not look as if any code had been removed.

**Comment by tiziano88** [comment]
are you sure you built in the correct mode? If you built the Functions Loader with runner I think it would be in release mode, so you should try with `release_max_level_off`?

**Comment by conradgrobler** [comment]
I built using cargo build, and used both `max_level_off` and `release_max_level_off`:
```
log = { version = "*", features = ["max_level_off", "release_max_level_off"] }
```

**Comment by conradgrobler** [comment]
I did some further testing, including your suggestion of logging some magic string and grepping for the string in the resulting binary (the string is still there even with the featrues enabled).

So, enabling the features seems to disable all loging via the `log` crate, but it does not completely remove all the logging-related code from the resulting binary.

**Comment by tiziano88** [comment]
Interesting, is that even in release mode? I wonder if these constants are only stripped when optimizations are on.

In any case, what do you suggest we should do?

**Comment by conradgrobler** [comment]
Ah, good point. In release mode it does get stripped out.

I think we should create our own explicit logger as a first step and add the features to switch off logging. This will stop dependencies from logging via the `log` crate. We can later add additional protections based on the comments above by @alastairreid to detect additional potential leaks.

**Comment by tiziano88** [comment]
Sounds good, are you going to look into creating the capability-based logger?
