### ISSUE TITLE
Add ABI function and SDK support for logging

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1977]
Add an ABI function to allow logging from Wasm modules using `Logger::log_sensitive`.

If would also be useful to add a logger and log configuration logic to the SDK to use this ABI function, so that Wasm modules could use the `log` crate.

**Comment by tiziano88** [comment]
Another thing that we may consider for production logging is to accumulate the log statements during the invocation of a Wasm function, and return them alongside the response body to the client (perhaps in a separate header -- also subject to policy constraints of course (#1987). Perhaps the client may send a special header to allow debugging, and in that case it receives the logs as part of the response. Note that allowing debugging in this case really just means sending the debug logs back to the caller, i.e. it does not allow the server to relax any policies. The client ultimately decides what to do with the resulting logs, e.g. whether to print them locally or anything else. Note that in general, logs must always be considered sensitive, since a client would not be able to determine whether the content of the log entries were based on the request (e.g. in the weather lookup example, a malicious Wasm module may log something slightly different based on whether the user location is in a specific country).

**Comment by tiziano88** [comment]
@conradgrobler is this done?

**Comment by conradgrobler** [comment]
The logging itself it done. The last comment on sending back logs to the client for a special debug header is not done, bat as far as I can remember we decided to leave that up to the client and the Wasm code and not do anything special in the runtime (apart from allowing the client to increase the response size policy).

**Comment by tiziano88** [comment]
Yeah I don't think we need special support for that, it can be implemented by applications if they want, for now.

**Comment by tiziano88** [comment]
Although, that's probably a bit in conflict with the log support in the SDK; would an application use the SDK, or do they have to roll their own manual logging throughout?

**Comment by conradgrobler** [comment]
We could add support to the SDK to collect a copy of all logs so that the application could retrieve it when writing the response.
