### ISSUE TITLE
Allocate new port for each Oak Node instance

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2]
Currently the Oak Scheduler creates new Oak Node instances all listening on the same port (see
https://github.com/project-oak/oak/blob/c9c13c3c27cdcbdf8a1f082b8937262eba7708a3/oak/server/enclave_server.h#L107), which means that when a client attempts to connect to it and there are multiple Oak Nodes listening there, the client will be connected to an arbitrary Oak Node among those running there.

We should instead let each Oak Node pick a free port on the host, and return that as part of the scheduling response.

Note the main reason why we have not done this yet is because we run the Oak Scheduler in Docker, and we need to list in advance all the ports to expose (see https://github.com/project-oak/oak/blob/c9c13c3c27cdcbdf8a1f082b8937262eba7708a3/scripts/run_server_docker#L16)

**Comment by liulu1124** [comment]
To recap a discussion I had with @tiziano88 

1. The obvious problem as stated in the bug is that every Oak Node's GRPC port number needs to be one published by Docker environment;
2. A further complication is that a Docker container port can be mapped to a different host port (see [doc](https://docs.docker.com/config/containers/container-networking/#published-ports)); In this case OakManager needs to write the mapped host port in [CreateNodeResponse](https://github.com/project-oak/oak/blob/master/oak/proto/manager.proto#L32) in order for the client to be able to contact the Oak Node.

One possible option is to publish a range of ports in docker and use exact container to host port mapping; this range is passed to OakManager, which can choose from a list of "free" ports in the range and pass it to the new enclave via [InitializeInput](https://github.com/project-oak/oak/blob/master/oak/proto/enclave.proto#L23) proto

Beyond the limitations this method imposes on configuring Docker, it also has the drawback that the "free" port number might not actually be free if they collide with ports already in use (e.g. 8888 is already used by manager's own GRPC server, or well-known ports); to alleviate the situation we could potentially test if a port if free in OakManager before passing it to the new enclave

**Comment by michael-kernel-sanders** [comment]
"When running using --network host there is no need to map the ports. All the docker container ports will be available since the network host mode makes the container use the host's network stack."

https://stackoverflow.com/questions/49323225/expose-all-ports-for-a-docker-image

**Comment by tiziano88** [comment]
Thanks, that is interesting! Does it mean we can keep using `:0` and the stack within the container should be shared with the host so that new ports are consistently assigned and guaranteed not to clash? Thinking of that, I am not even sure how that is implemented internally, I assume the kernel has some synchronized state to prevent multiple concurrent bindings to `:0` to be assigned the same port?

**Comment by tiziano88** [comment]
Uhmm I think @liulu1124 is talking about the Oak Manager (outside of enclave), and @michalgorn about the Oak Node (inside enclave)?

**Comment by liulu1124** [comment]
Ummm actually I did the same thing as @michalgorn, not sure why it's not working for me

**Comment by tiziano88** [comment]
@liulu1124 are you sure your `:8888` port is _actually_ free on your host? maybe you have a previous instance of the Docker container still running, or something else?

**Comment by liulu1124** [comment]
Yeah I changed the manager listening port to something like 12345 and it worked; You're probably right about another docker instance occupying the ports.

Anyways great to know there's a straightforward way of resolving this issue!

**Comment by tiziano88** [comment]
Closed via #46
