### ISSUE TITLE
Consistent log and panic messages

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2119]
There does not seem to be an agreed standard for panic and log messages in Rust, and we already have quite a few inconsistencies within our code base.

I suggest we pick a format and try to stick to it; for instance, this is the closest I could find to a style guide for error messages:
https://docs.rs/serde/1.0.126/serde/de/trait.Error.html#tymethod.custom

> The message should not be capitalized and should not end with a period.

**Comment by vsouleles** [comment]
So, I searched for some standard/convention/common practice for log messages in Rust but I couldn’t find any.  A [discussion in Reddit](https://www.reddit.com/r/rust/comments/fv7830/panic_message_conventions/) yielded that other people are also looking for a common style but there aren’t any established conventions.

As Tiziano said, the format described in [the serde docs](https://docs.rs/serde/1.0.126/serde/de/trait.Error.html#tymethod.custom) is:
> The message should not be capitalized and should not end with a period.

And it matches, for example, with the Rust style used in [the fuchsia documentation](https://fuchsia.dev/fuchsia-src/development/languages/rust/logging#recording_messages).

This style makes sense, especially if the code follows the `error!("function failed because: ", reason);` format  .

The end result will look like this:
```
[2021-05-24 21:42] foo failed, error: bar couldn’t acquire lock, reason: baz timed_out, exception: DEADLINE_EXCEEDED
```

It may not the prettiest thing in the world, but it's readable, concise, and it's in a single-line thus grep-able.

Overall, consistency is key, so I suggest we pick this style and stick to it for the entire project.

Let me know if I missed some other style that is common among Rustaceans, otherwise I will send a PR to apply the above style in the existing codebase.

**Comment by tiziano88** [comment]
LGTM, let's go with that :) I think this should apply both to log statements (e.g. `log::info!(...)`) as well as `panic!(...)` and also `.expect(...)` and `.context(...)`. 

Bonus points for figuring out how to maintain this style over time, e.g. via a linter step (even if it's just regexp based for now).

**Comment by vsouleles** [comment]
I'm trying to come up with a regex-based linter that will verify the consistency of the messages in the codebase, similar to [check_todos.rs](https://github.com/project-oak/oak/blob/main/runner/src/check_todo.rs).

Rust can be quite [flexible](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=41ff5063fe6ccc078c161dcf94d3d1aa) so it would be difficult to catch all cases using a regex-based linter. Instead, a possible first iteration for the linter could be to catch the cases found in the codebase:
```
// same line
error!("Some error occurred");

// next line
panic!(
    "Failed to do x and y and z and this is a really long line");
```

Moreover, adding `// NOLINT` into the mix can be a bit tricky (as far as I can tell) for a regex-based linter, unless it's in the same line with the upper-cased string literal:
```
// Non-trivial case to parse using regular expressions.
// Would have to consume everything, including new lines,
// up until the first non-escaped non-commented right_paren(?) or semicolon(?)
// and then consume everything up to the end of the statement(?)
// and then see if there is a "// NOLINT" before the end of that line.
info!(
"A string literal starting with an upper case",
"and then some",
"Some more",
foo,
42)
.foo(bar); // NOLINT

// Somewhat easier to parse using regular expressions.
// The `// NOLINT` goes in the same line with the upper-cased string literal.
info!(
"A string literal starting with an upper case", // NOLINT
"and then some",
"Some more",
foo,
42)
.foo(bar);
```

I've created [a simple PoC](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ede85d17de831e502fa288761531dedc) that you can play with. What do you think?

**Comment by tiziano88** [comment]
Thanks @vsouleles for the write up and the prototype. I wonder whether implementing an actual linter as a rust compiler plugin instead of regexps would actually be simpler and more idiomatic: https://doc.rust-lang.org/beta/unstable-book/language-features/plugin.html . In fact it seems that if such plugin existed, probably also other projects would use it. Do you think it would make sense to give it a try?
