### ISSUE TITLE
Export Differential Privacy based values from Oak Functions

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2244]
We should experiment with exporting values during the execution of an Oak Functions module, subject to Differential Privacy (DP) constraint (e.g. epsilon-delta).

For now we can start with allowing the module to export a single boolean value, having the runtime collect those values from various executions over a time window, aggregate them and add sufficient noise to meet the DP constraints for the instance, and finally export them (for now we can log them or export them as metrics).

The time window and the DP parameters should be specified in the configuration file, and they should also be provided by the runtime to the client as part of the remote attestation step (#2243), so that a client is able to detect whether this API is enabled (and with what parameters) *before* sending any data to it.

**Comment by conradgrobler** [comment]
I think we could start with just using Laplacian noise, which would provide epsilon-differential privacy and is stronger than epsilon-delta. Gaussian noise and epsilon-delta-differential privacy could become useful if we distribute the privacy budget over a larger number of labels (Laplacian noise requires scaling epsilon by 1/k per label for k labels, Gaussian noise only requires scaling by 1/sqrt(k)).

My current plan for an initial version is:

- Add an ABI function to report an event with a label (e.g. "error")
- Each Wasm instance can report an event for each label at most once (additional reports are ignored)
- Add configuration option to specify allowed labels and an epsilon privacy budget that will be equally shared over all of them
- Any event reported for a label that is not explicitly allowed is just ignored
- Add configuration option for the reporting batch size
- Once enough Wasm instances have run to match the batch size: calculate the count of event reports for each label, add Laplacian noise based on the label's share of epsilon and log the result

Possible future enhancements
- Option to use Gaussian noise and epsilon-delta parameters
- Allow choosing between batch size or time window to define batched releases
- Allow specifying sub-budgets for labels (e.g. allowing "error" labels to user more of the budget than others)
- Export the results as metrics rather than just logging them

**Comment by conradgrobler** [comment]
One additional potential future enhancement is to support labels that can use predefined integer ranges, rather than just 0 or 1. Values outside the range will be clamped to the limits of the range and noise would be scaled by the size of the range allowed for the specific label.

**Comment by tiziano88** [comment]
As long as we treat the values as discrete elements of a set (i.e. we do not assign numeric meaning to them by calculating average / max / min and other arithmetic operations over them), we can just configure a list of labels, and for each label a list of allowed values, either as strings or as numbers, if it's more convenient. But even in the numeric case, I would not clamp the values, in fact I would not consider them as numbers at all, just as opaque symbols for elements in a set of allowed values. If the code emits an invalid value, it will just be discarded / ignored.

**Comment by conradgrobler** [comment]
The differentially private metrics code has been deleted from the repo.
