### ISSUE TITLE
benchmark for weather lookup example

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2264]
Implement a test / benchmark that measures the time it takes for the weather lookup example to process a single request.

Ideally the test also generates the database from some configurable parameters (using the logic from https://github.com/project-oak/oak/tree/main/oak_functions/lookup_data_generator if possible) and is fully hermetic, i.e. without downloading the data from Cloud Build.

ref: https://github.com/project-oak/oak/blob/f8eccbd08c19af3e596132c472e37b8fd9300fb5/oak_functions/loader/src/tests.rs#L245

**Comment by rbehjati** [comment]
Is benchmarking a single request enough for understanding the performance of the weather-lookup application, or do we in addition need a load testing similar to #1986 specifically for weather lookup?

**Comment by conradgrobler** [comment]
I think we need to do load testing with for the end-to-end process including the RA/handshake as well, but we should probably track that separately. I can think of at least two different versions of such load test: one with an unsafe version that does not apply policy so that we can check the bounds on actual latency. The other with the policy enabled to monitor performance characteristics on the server while under heavy load.

**Comment by rbehjati** [comment]
Good point about experimenting with/without policies.

**Comment by conradgrobler** [comment]
I created #2267 to track load testing.
