### ISSUE TITLE
Add `./script/runner presubmit`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#2403]
Add a presubmit fast enough to be run locally (<5 min). 

Ideas (summarizing #2390 ):
- seperate `oak_functions` and `classic_oak`
- add `run-cargo-fuzz --build-deps -- -max_total_time=2`
- `classic_oak` updates hashes/signatures in examples if changed.

**Comment by rbehjati** [comment]
I think for `oak_functions` a presubmit job that runs locally would run:
* `run-cargo-tests`
* `run-functions-examples --application-variant=rust`
* `run-cargo-fuzz --build-deps -- -max_total_time=2`
* `format`

All with the `--commits=N` flag. 

For `classic_oak`, we'd want the following commands:
* `run-cargo-tests`
* possibly `run-bazel-tests`
* `run-examples --application-variant=rust` and possibly `run-examples --application-variant=cpp`
* An additional command for updating the hashes and signatures in the examples. 
* `format`

All with the `--commits=N` flag. 

In addition to supporting the `--commits` flag, commands such as `run-cargo-tests` and `format` should take a new flag so that they can be run only for `oak_functions` or classic oak (i.e., everything other than the `oak_functions` workspace).

**Comment by mariaschett** [comment]
Won't fix, as #2455 fixes this sufficently.
