### ISSUE TITLE
Unify Rust workspaces

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2475]
I think https://github.com/project-oak/oak/pull/2473 would be much more effective and efficient if all the crates were under a single workspace.

IIRC the only reason for having separate workspaces was to make it easier to keep deps separate, but I think we agreed that we may not care about that, as long as, for instance, we can list the exact versions of the deps used by the oak_functions_loader binary, even if it belongs to that workspace.

Or am I forgetting something else? @project-oak/core

**Comment by mariaschett** [comment]
So yes, I had the same idea with [Oak functions to workspace](https://github.com/project-oak/oak/pull/2361).

Two things to consider:
1. I am not sure we can have different versions of a dependency in the same workspace, so we may be stuck with an old dependency.
2. The location of the target folder will change (maybe the name of the binaries too).

**Comment by mariaschett** [comment]
about 1. it seems you can have different versions [see](https://stackoverflow.com/questions/51714866/is-it-documented-that-cargo-can-download-and-bundle-multiple-versions-of-the-sam)

**Comment by rbehjati** [comment]
Adding some more context, since the team hash had similar discussions in the past, for instance #534. 

Also, at some point we had a single workspace, or at least fewer ones, and we split that into the workspaces that we now have: #1034, #1039, #1045, #1063, #1122, etc. Some of these issues are linked to #971. So I guess we made these separated workspaces to fix the cache invalidation problem.

**Comment by jul-sh** [comment]
My two cents wrt keeping deps separate, I actually think that not being able to do so can be a good thing sometimes. This is because it increases the cost of maintaining dead code, as it requires updating when updating deps with breaking changes. Which then creates a general incentive to be mindful about what should or shouldn't continue to be in the repo. :)

**Comment by tiziano88** [comment]
I don't think anything would change wrt to keeping deps separate or unifying them. It is already possible to depend on different versions of the same crate within a given crate, and by extension also from crates in the same workspace. So I think this proposal is orthogonal to your point (which is valid). Or did I miss your point @jul-sh ?

**Comment by jul-sh** [comment]
@tiziano88 nope, you understood it correctly. I should clarify that I was prompted to write that as an aside purely bc of you wrote above "IIRC the only reason for having separate workspaces was to make it easier to keep deps separate". I didn't mean to imply that this change would indeed have the effect of making the maintenance of separate deps impossible.
