### ISSUE TITLE
Integrate Scorecards

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2563]
See https://github.com/ossf/scorecard-action

cc @aferr @rbehjati

**Comment by tiziano88** [comment]
To clarify, this would be about setting up the Scorecards GH actions for our own repo.

**Comment by aferr** [comment]
@rbehjati let me(/us) know how that goes.

**Comment by tiziano88** [comment]
Done, I create a PAT as per https://github.com/ossf/scorecard-action#authentication and set that as the secret, is that what you needed?

**Comment by rbehjati** [comment]
I think so. But there is [this error](https://github.com/project-oak/oak/runs/5464946628?check_suite_focus=true) related to the token. Is it supposed to only work on the `main` branch by any chance?

**Comment by tiziano88** [comment]
I would expect so, otherwise anyone would be able to read the token by sending us a PR that just logs it

**Comment by rbehjati** [comment]
Thanks :)

**Comment by rbehjati** [comment]
@aferr We now have scorecards set up for the project, and we are getting some reports, but I am not entirely sure how to interpret the results, or where to find the average score for the entire repository. Do you know how exactly we could use the scorecards?

**Comment by aferr** [comment]
Is your question more at the implementation level or design level?

At the design level, I think either way scorecards are used to make claims about the repository / source code (or similarly I think they can be interpreted as claims about the provenance file because provenance files are about the source code). (Then ideally we use some common set of authorization logic rules to take claims about provenance files and generate claims about binaries when the right conditions are satisfied / all the right checks pass). These could be interpreted as authorization logic statements. Then we can either use scorecards in a fine-grained way or a coarse-grained way:
 - coarse-grained: we take the final score output and interpret this as something roughly like `"scorecards" says "provenance_file::oak_functions_loader" hasScore("8.5").` 
 - fine-grained: we decouple the individual checkers [here](https://github.com/ossf/scorecard/tree/main/checks) and use them to produce more narrowly scoped facts like `"scorecards_fuzzer" says "provenance_file::oak_functions_loader" passes("fuzzTesting")`. Then parties deciding when to use a repository can set policies that use these more fine-grained facts.

I would guess the coarse-grained way is less work, but the fine-grained way gives us more value potentially. The fine-grained way is also only useful if anyone is willing to write more fine-grained policies about deciding if a repo is acceptable, and IIRC we are not at this milestone yet. Perhaps the coarse-grained way is the better starting point and we can try the fine-grained way if it still seems appealing to do so when we approach the milestone where we want policies involving claims about the repository/binary.

If your question is more at the implementation level, like how exactly to parse the results they generate, then I have not yet used their tools enough to know.

**Comment by rbehjati** [comment]
Thanks. I agree with your description of integrating scorecards with authorization logic :)

My question is actually at the implementation level. In particular how can we extract something like `"provenance_file::oak_functions_loader" hasScore("8.5")` from the scorecards reports? We have the [code scanning alerts](https://github.com/project-oak/oak/security/code-scanning), but I don't see any actual scores there! There are some score-looking numbers in the output SARIF files (e.g., [here](https://github.com/project-oak/oak/suites/5641615529/artifacts/184319674)), but it is not clear to me how to interpret those numbers, for instance security-severity:

```
...
 "properties": {
   "precision": "high",
      "problem.severity": "error",
      "security-severity": "7.0",
      "tags": [
         "supply-chain",
         "security",
         "dependencies"
      ]
 }
...
```

**Comment by aferr** [comment]
OK got it. I don't know enough details to answer this question directly, yet. I can look into it a bit as well. I will probably not prioritize it highly unless there is a there is a reason to do it more urgently, though :) (so let me know if there is some reason).

**Comment by rbehjati** [comment]
Not urgent really, but let us know if you find anything :)
