### ISSUE TITLE
Current version of wabt relies on `assert`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#276]
It seems that `wabt` relies on `assert` for input validation and precondition checking.

This gets in the way of fuzzing, because assertions abort the binary immediately and are detected as failures by the fuzzer engine.

From a quick look it seems that newer versions of `wabt` removed those `assert`s, so maybe we should try upgrading to a more recent version.

#261

**Comment by tiziano88** [comment]
@blaxill I think this will be fixed when upgrading `wabt` to a newer (/ latest) version, as a follow-up to #332 .

**Comment by blaxill** [comment]
I have a branch at https://github.com/blaxill/oak/tree/wabt-update which builds/tests work, but currently hangs on abitest.cc.

**Comment by blaxill** [comment]
Execution log : https://gist.github.com/blaxill/ae7a20f254aba48dfebd53a3d5939159

**Comment by daviddrysdale** [comment]
(Transcribing discussion for future reference)

The client hangs because the Node fails to run, with:
```
2019-12-10 15:11:44  ERROR  wasm_node.cc : 264 : {backend_0} execution failure: uninitialized table element
```

This looks to be [this error](https://github.com/WebAssembly/wabt/blob/master/src/interp/interp.h#L54-L55) from [here](https://github.com/WebAssembly/wabt/blob/master/src/interp/interp.cc#L1921), added in https://github.com/WebAssembly/wabt/pull/1206 as part of the implementation of a new Wasm ["reference types" feature](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md#language-extensions).

Would pulling in a specific release (e.g. [1.0.12](https://github.com/WebAssembly/wabt/releases/tag/1.0.12)) rather than `master` avoid the problem?

**Comment by blaxill** [comment]
Yup, 1.0.12 doesn't include a number of wabt interface changes and is the most recent release so I'll pin to that. 

I'll the master version around at https://github.com/blaxill/oak/commits/wabt-update-save to remind myself of what needs changing when we update in the future.

**Comment by tiziano88** [comment]
I think this can be closed now, right?

**Comment by blaxill** [comment]
Wabt still uses assert, I'm afraid I'm not sure which ones were previously causing issue. Perhaps we should wait for feedback from the fuzzer?

**Comment by tiziano88** [comment]
It seems that the fuzzer is not complaining about this any more, so at least the asserts we care about are gone. @blaxill could you confirm and close this issue if that's the case?
