### ISSUE TITLE
Create flatbuffers without copying the underlying buffer

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2945]
At the moment we copy the entire buffer from the flatbuffer builder into the wrapper `Message`. See https://github.com/project-oak/oak/blob/main/oak_idl/src/utils.rs#L95

We should be able to use https://docs.rs/flatbuffers/latest/flatbuffers/struct.FlatBufferBuilder.html#method.collapse to get ownership of the underlying owned buffer.

**Comment by jul-sh** [comment]
Looked into this a bit, I'm not sure it's realistic.

The difference is that the current reallocation solution ensures that the valid data in the buffer always start at index 0. That's not the case with `collapse`, which returns a tuple of the underlying buffer and the position where the valid data starts (flatbuffer will need to know this when parsing the underlying buffer again at a later point).

In the IDL, methods are invoked with the underlying buffer. If we change to using `collapse`, the call signature of methods would need to be updated to accept the tuple of buffer + position. 

In the transport layer we'd also need to send over the pos alongside the message buffer. And if we do that we're effectively ending up with unused data prefixing each message, decreasing efficiency.

I did find another small issue I was able to fix though. Atm reponse messages are copied twice. Once when converting from a flatbuffer builder to a message (what this issue is about), and then again at a later point (fixed by #2953).

**Comment by jul-sh** [comment]
One potential solution to the above would be if we could take the owned larger buffer returned by `collapse`, and split it into a smaller buffer without copying. Not possible in safe rust, but maybe possible with unsafe rust.

**Comment by conradgrobler** [comment]
I think it is worth experimenting a bit, e.g. understand how much extra space is in the buffer if we collapse a builder that was finished and contains a root message. If it is only a few bytes for alignment it might be worth it to avoid the additional copies.

Also, we will already have to copy at least once when using virtio for comms. Virtio running under AMD SEV-SNP will need to use buffers in memory pages that are shared with the hypervisor so that it can be read. Our general processing will happen in these shared pages, so it might be worth carrying the additional information around until we copy to the virtio buffer, at which point we could remove the additional info.

**Comment by conradgrobler** [comment]
We are no longer using flatbuffers
