### ISSUE TITLE
Use Rust new x86 bare metal target

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3015]
From https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#bare-metal-x86_64-target:

> It's now easier to build OS-less binaries for x86_64, for example when writing a kernel. The x86_64-unknown-none target has been promoted to Tier 2 and can be installed with rustup.

Is this something that would simplify our build process?

Feel free to close if this is not helpful after all

**Comment by andrisaar** [comment]
I've already had a go playing around with that :)

Unfortunately it won't work for us, as we need to enable AVX, and the default x86_64-unknown-none doesn't support that.

(Mind you, I think we should get rid of AVX in kernel code, and switch the kernel to x86_64-unknown-none. But that will happen once we manage to sort out what userspace would look like, so that we can build the runtime with different compiler flags.)
