### ISSUE TITLE
Implement constant time policy support freestanding Oak Functions runtime

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3079]
Also allow configuring it via the init message in the IDL:

https://github.com/project-oak/oak/blob/dd2dc6b1cae87e8210a4f532d040fb70d27f69ca/experimental/oak_baremetal_channel/schema.fbs#L23-L25

Note this is qualitatively harder than #3078 because it requires figuring out how to deal with timers in the bare metal environment.

**Comment by tiziano88** [comment]
Yes, I meant if there is a task tracking the multi CPU support at least for now.

Although it may also be possible to emulate something similar using interrupts maybe? But I'm not sure if it's even worth looking into.

**Comment by conradgrobler** [comment]
I don't think using interrupts would be worth it at the moment. I created a task for supporting additional vCPUs.

**Comment by tiziano88** [comment]
I'm thinking of an alternative approach that does not rely on timers in the TEE: instead of synchronously responding to the request from the untrusted launcher, we could separate the interaction for each client request into two parts (each modeled as an RPC from the untrusted launcher):

- initiate processing: send the contents of the (encrypted) user request, immediately receive a confirmation that processing started
- fetch result (and interrupt processing if still running): at a later point (controlled by the untrusted launcher), send a request asking to retrieve the current result of the computation (by session id, or some other id); this returns either the actual (encrypted) response, or an (encrypted) error message if the actual response is not ready yet

**Comment by conradgrobler** [comment]
It should work, but at the moment the untrusted launcher treats messages from clients as opaque blobs that it just proxies through. This approach would mean that the untrusted launcher must understand the communications between the client and the trusted runtime to some extent. At the very least this would require that the untrusted launcher can distinguish a handshake message from an invocation message, which I don't think is always possible with our current protocol. The trusted runtime keeps state about each session (whether the handshake is in-progress or completed) to help with this, but the untrusted launcher does not have access to this state. The simplest way to achieve this would be to add a fixed byte to the start of every invocation message so that it can be easily detected (in the same way that each step of the handshake is identified by an initial byte).

**Comment by tiziano88** [comment]
This issue is still relevant (though not super high priority).

Now that @mariaschett updated wasmi to a recent version, I think we could use the fuel mechanism to be able to get back execution from a running Wasm module (rather than letting it run forever, e.g. if it gets stuck in an infinite loop).

See https://docs.rs/wasmi/0.29.0/wasmi/struct.Config.html#method.consume_fuel
