### ISSUE TITLE
Support loading a linux binary as a child process in bare metal loader

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3080]
Currently the bare metal loader supports loading the trusted runtime in either QEMU or crosvm.

@conradgrobler suggested we should add support for spawning a trusted runtime instance (of the appropriate format) as a linux child process on the same host (i.e. without virtualization needed). This would allow us to keep developing a more fully featured version of the oak runtime with additional functionality like TF inference and differentially private metrics, which would otherwise be nontrivial to get to work in an actual bare metal environment.

As a starting point, this would probably require adding a new value to this enum:

https://github.com/project-oak/oak/blob/dd2dc6b1cae87e8210a4f532d040fb70d27f69ca/experimental/oak_baremetal_loader/src/main.rs#L43-L46

The loader and the child process should communicate with each other over a channel that follows the existing IDL interface, though it may be implemented via a Unix Domain Socket, a network socket, a named pipe, a pre-opened file descriptor, stdio, or some mechanism.

**Comment by jul-sh** [comment]
I'd be curious of you had thoughts about including the trusted runtime as a library in the launcher, instead of spawning a separate child process? Communication could still take place over the IDL, but instead of a UDS the channel would simple buffer (eg `std::io::Cursor<std::vec::Vec<u8>>`. 

In principle that seems simpler and more straightforward?

**Comment by conradgrobler** [comment]
It feels problematic to include a library that will mostly be unused (only used for non-production testing). I guess that could be solved via features, but features on a binary crate causes other problems (e.g. not easily being able to tell which features were enabled when the binary was built, as the name remains the same)

While it might simplify some things, it might complicate others because the model for starting and stopping the runtime would be different.

**Comment by jul-sh** [comment]
Fair. :) I mean arguably the OSS untrusted loader as a whole will be mostly used for non-production testing at the moment, but I get the point about a separate binary creating a more obvious and clearer seperation. :)

**Comment by jul-sh** [comment]
Fixed with #3106
