### ISSUE TITLE
Create custom target file for Oak freestanding binaries

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3523]
See https://docs.rust-embedded.org/embedonomicon/custom-target.html

It would be nice to define a target like `x86_64-unknown-oak`, based off `x86_64-unknown-none`, in which we can embed the modifications that are currently expressed as extra flags in cargo config files. Ideally we would probably need another target for stage0, but for now we can keep using plain `x86_64-unknown-none` for that (it is technically accurate, even though we do require some more changes to that too:

https://github.com/project-oak/oak/blob/dd3be6ab3e9c47844869ff5807aca0ee1d8c360a/stage0/.cargo/config.toml#L5

@andrisaar @conradgrobler WDYT?

**Comment by conradgrobler** [comment]
We used to have a custom target.json file and moved away from it once the x86_64-unknown-none became available. I can't remember the details, but it did cause a few annoyances at the time. @andrisaar  might have a better recollection of the issues we had with it.

**Comment by andrisaar** [comment]
I'd shelve this for the short term. Once we have a proper userspace for the Restricted Kernel, then we should definitely see what it takes to define a `x86_64-unknown-oak` for the binaries that are supposed to be executed under Restricted Kernel,
while the kernel itself (and stage0) would keep using `x86_64-unknown-none` (which is also the semantically correct one for them).

Otherwise, yes, these override have to go somewhere and if anything I spent quite some time getting rid of that custom .json file completely, and thus some flags had to move to `.cargo/config.toml`.
