### ISSUE TITLE
Only serve requests after Lookup Data is fully loaded

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3615]
Check whether `Oak Functions` only serves requests after the lookup data is fully loaded.

If this is the case, add comments to the code explaining and linking to the invariant in the README.

**Comment by conradgrobler** [comment]
That is a good point. This is a quality of service requirement, not a safety requirement, so the untrusted launcher must decide when to start serving. Since we want to be sure the lookup data is in an expected state after each batch of lookup data was loaded, we should return that as part of the result to when loading lookup data. The launcher can then use this information to decide whether it should start serving requests.

**Comment by mariaschett** [comment]
Yes, but the untrusted launcher _can_ start passing requests before the lookup data is fully loaded. 

What do we want to do if the untrusted launcher gives a lookup request to Oak Functions before the lookup data is fully loaded (assuming that Oak Functions can determine the lookup data is not yet fully loaded)?

>  I'm not even 100% sure it is necessary in the first place

I'd argue Oak Functions should reject _all_ (lookup) requests---and I think this needs to be an invariant upheld by Oak Functions.

Otherwise, the Untrusted Launcher can selectively hold back loading of lookup data and observe which clients are forced to retry. 

But maybe we do not mind this?

**Comment by conradgrobler** [comment]
Thinking about this a bit more: the Oak Functions trusted application can't really not serve requests, only return errors instead of processing them. I think that it should return errors if it is sent any requests before it has fully initialised.

If the decision whether to try to look up data is based on user request data I agree that seeing a user retry will leak information, so I think that if the initial lookup data has not been fully loaded it should return an error, rather than execute any Wasm logic.

This probably means that we need to add something to the trait for extensions so that the application can ask each extension whether it is fully initialised before it starts handling requests without automatically erroring.

**Comment by tiziano88** [comment]
I still don't think the trusted application needs to do anything different at all.

The untrusted launcher sends the lookup data (which is a synchronous operation, so it knows when it's done by receiving an ack message back via microRPC), and then starts sending user request. If there is no lookup data to load, the launcher can just send requests instead, there is no concept of "holding things back".

**Comment by mariaschett** [comment]
> there is no concept of "holding things back".

The untrusted launcher can simply not give parts of the lookup data to Oak Functions, no?

And assuming Oak Functions knows it is not fully initialized, i.e., does not have all lookup data loaded: What will Oak Functions do when it receives a request?

**Comment by mariaschett** [comment]
We intialize the WasmHandler [here](https://github.com/project-oak/oak/blob/4e099517972ea1afe94b1c03f6723fc2a359507f/oak_functions_service/src/lib.rs#L86), which creates a lookup factory [here](https://github.com/project-oak/oak/blob/4e099517972ea1afe94b1c03f6723fc2a359507f/oak_functions_service/src/wasm/mod.rs#L30) which leads to [creating lookup data](https://github.com/project-oak/oak/blob/4e099517972ea1afe94b1c03f6723fc2a359507f/oak_functions/lookup/src/lib.rs#L55). Afterwards Oak Functions is initialized.

If Oak Functions gets a request before being initialized, it returns an error [here](https://github.com/project-oak/oak/blob/4e099517972ea1afe94b1c03f6723fc2a359507f/oak_functions_service/src/lib.rs#L127).

So I think we are all good, if [create lookup data](https://github.com/project-oak/oak/blob/4e099517972ea1afe94b1c03f6723fc2a359507f/oak_functions/lookup/src/lib.rs#L135) only returns after it has loaded all lookup data.

**Comment by mariaschett** [comment]
Update:

We are initially creating a [`DataManager` with empty lookup data](https://github.com/project-oak/oak/blob/c45ea071acf9dbb75a639b99fce386d99892c089/oak_functions_service/src/lib.rs#L58) data in `OakFunctionsService`.

I think, our first loading of lookup data, and all consecutive updates, happen _asynchronously_ [here](https://github.com/project-oak/oak/blob/c45ea071acf9dbb75a639b99fce386d99892c089/oak_functions_launcher/src/main.rs#L122-L140).

So I don't think we are currently waiting until all lookup data has loaded. 

Or am I missing something @conradgrobler , @tiziano88 ?

**Comment by conradgrobler** [comment]
I think you are right. It happens to work right now, since the lookup data is small and it is triggered before whe Wasm is uploaded, but I don't think this will work with larger lookup data.

**Comment by tiziano88** [comment]
Good catch @mariaschett , you are right, we should fix that. More importantly, we should check what the behavious is on the C++ untrusted launcher (I don't think we have async support there, but I'm not sure in what order we do things anyways).
