### ISSUE TITLE
Avoid copying lookup data chunk

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3791]
We may be able to avoid this copy, if we can get ownership of the request.

**Comment by tiziano88** [comment]
We can make microRPC consume the request if it helps here -- I thought that in most cases it does not make a difference since there is usually at least another copy made somewhere anyways.

To confirm: do you think here we would be able to avoid all copies, if we take that request by value? I thought the map would end up copying it anyways (but not 100% sure).

If so, could you file a GH issue to track the microRPC change?

**Comment by mariaschett** [comment]
> do you think here we would be able to avoid all copies, if we take that request by value?

I haven't yet figured out, whether [extending our underlying hash(brown) map](https://docs.rs/hashbrown/0.13.2/hashbrown/hash_map/struct.HashMap.html#method.extend) copies the data. 

I'll try to pass a reference of our data to `extend`, if I understand one of their [tests](https://docs.rs/hashbrown/0.13.2/src/hashbrown/map.rs.html#7645) this should be possible.

**Comment by jul-sh** [comment]
> I think we need to copy the [chunk of lookup data](https://github.com/project-oak/oak/blob/1fd2accd09a52a9b7b55e798a99ba45236a1862d/oak_functions_service/src/lib.rs#L152), because the `request: &schema::ExtendNextLookupDataRequest` is only borrowed, and not moved.

I had a look at this, after we talked about it offline. I'm confident that the changes suggested in https://github.com/project-oak/oak/issues/3848 would not help this issue. 

That's because the code in linked here runs in the service implementation, not in the client code.
