### ISSUE TITLE
Make MicroRPC consume the client request

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3848]
Avoid copying the request, by making [`client_invoke`](https://github.com/project-oak/oak/blob/1fd2accd09a52a9b7b55e798a99ba45236a1862d/micro_rpc/src/lib.rs#L107) and [`async_client_invoke`](https://github.com/project-oak/oak/blob/1fd2accd09a52a9b7b55e798a99ba45236a1862d/micro_rpc/src/lib.rs#L146) consume the request instead of expecting a reference.

#3791 .

**Comment by jul-sh** [comment]
I don't have a strong opinion on this as it stands right now. My impression is that borrowing is a remnant from when we used flatbuffer. Though I do think your (@tiziano88) argument that it sometimes may still be useful holds true.

Either way (updating only the existing method or duplicating all methods) would be significant refactoring work. 

It depends on how critical #3791 is. If avoiding copying there is just a nice to have (eg no performance bottleneck atm) I would be inclined to leave it as is for now.

**Comment by mariaschett** [comment]
Re: how criticial #3791 is. We are now trying to load 300 GiB of lookup data---of which we make, as far as I see, a superflous copy here.

We definitely have a problem of using a lot of memory when loading lookup data. My initial impression is, we have an overhead of about 8 GiB to copy 2 GiB (b/267994105).

What I am not sure about, is whether this is the greatest win, or we could/should focus on other improvements first.

Do you have an idea, @jul-sh , on how much work would it be to refactor?

**Comment by jul-sh** [comment]
You'd probably have to edit the packages related to micro_rpc. It's bit cumbersome since they generate code, but should be doable. Ideally it should be possible to pass either a reference or an owned request.

There's another issue as it stands though. Namely within the function we call the `encode_to_vec` method on the request. Even if the request were owned, that call would still result in a new allocation. (see https://docs.rs/prost/latest/prost/trait.Message.html#method.encode_to_vec)

By the looks of it the reallocation appears hard to avoid.

**Comment by mariaschett** [comment]
Good point,  @jul-sh , as you say, [`encode_to_vec` adds another copy here](https://github.com/project-oak/oak/blob/1fd2accd09a52a9b7b55e798a99ba45236a1862d/micro_rpc/src/lib.rs#L109) .

However, I still believe we can get rid of the copy described in #3791 if we address this issue (as the copy happens _before_ any call to invoke).

**Comment by jul-sh** [comment]
I had a look at https://github.com/project-oak/oak/issues/3791, after we talked about it offline. I'm confident that the changes suggested in in this issue as it stands right now would not help this #3791. 

That's because the code linked in #3791 concerns the implementation of the generated service trait. This issue proposes changing the type signature of the client code.

**Comment by mariaschett** [comment]
>  implementation of the generated service trait. This issue proposes changing the type signature of the client's methods

Oh, I probably introduced a x-y-Problem. I thought this issue (y) solves my x ( #3791 ).

> closing this issue

So I hoped to keep discussing x :) Do you think it would be better to start a new issue @jul-sh ?

**Comment by jul-sh** [comment]
> Oh, I probably introduced a x-y-Problem. 
It happens. :) 

> So I hoped to keep discussing x :) Do you think it would be better to start a new issue @jul-sh ?
If the aim is to solve #3791 we can probably talk about it there. It might turn out that we can solve it by making a different set of changes to micro_rpc, but it requires further investigation specific to #3791. I can try and debug #3791 if you'd like, though I'm not familiar with the lookup-data logic yet.

**Comment by mariaschett** [comment]
Great! Let's discuss on #3791 . 

I hope you don't have to understand too much about the lookup logic---it would be great to have your microRPC take on it :)
