### ISSUE TITLE
Use explicit crypto protos in the Oak service

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#4037]
Currently we have Hybrid Encryption protos:
https://github.com/project-oak/oak/blob/c797c2fdfc13690da8d978e7427ac9e97cfa8f33/oak_crypto/proto/v1/crypto.proto#L24-L33

That are used in the Oak service's `encrypted_body` as serialized bytes:
https://github.com/project-oak/oak/blob/c797c2fdfc13690da8d978e7427ac9e97cfa8f33/oak_remote_attestation/proto/v1/messages.proto#L96-L103

We might want to use explicit protos instead of serializing them and saving as bytes.

Ref https://github.com/project-oak/oak/issues/3442

**Comment by ipetr0v** [comment]
Correct, I just split the "explicit proto" part from https://github.com/project-oak/oak/issues/3843 as a separate issue.

**Comment by ipetr0v** [comment]
Arguments for using explicit protos:
- Makes all protos explicit and easy to read
- Proto serialization only done once, when the top level proto is serialized

Arguments against using explicit protos:
- If we'll update `oak_crypto` API to accept serialized protos, it will ease the use of `oak_crypto` crate by other creates
  - Because they won't have to depend on our protos
  - And it's complicated to expose a proto from a Rust crate loaded via Cargo

**Comment by ipetr0v** [comment]
cc @bmclarnon

**Comment by rbehjati** [comment]
I just managed to complete one simple example using our encryption libraries, and working with all these byte arrays instead of types was very confusing. Based on this, I think using actual types will improve developer experience, and make the library less error prone. 


> Arguments against using explicit protos:
> 
> * If we'll update `oak_crypto` API to accept serialized protos, it will ease the use of `oak_crypto` crate by other creates
>   
>   * Because they won't have to depend on our protos

But if they don't depend on the protos, the errors that could be caught at compile time, become runtime errors, which is even worse. Instead of this, we have to use a proper versioning mechanism to deal with breaking changes.

>   * And it's complicated to expose a proto from a Rust crate loaded via Cargo

What does complicated mean? Do you have a more detailed description somewhere?

>   * If they have to compile protos by themselves, it will create separate Rust classes (though with the same name)

This is bad, but there should be a way around it. Is it because prost puts the classes in randomly named modules?

> * We can update a proto without creating a breaking change in all dependent protos

How? Anyway. I don't think this is the right way to deal with breaking changes. I am guessing the cost of this kind of obscurity is going to be higher than the cost of dealing with breaking changes via correct and controlled versioning.

**Comment by tiziano88** [comment]
To work around the difference in the type resolution between protoc and rustc, I put together a proof of concept that shows how to make them work together: https://github.com/project-oak/oak/pull/4211

The trick is to have a stub for the types that makes protoc happy (the package and message names need to match, but not the location nor the internal structure). Then in the Rust code, embed the correct types from the oak_crypto crate in the place where rustc expects them.
