### ISSUE TITLE
Cannot build the Linux kernel with Nix

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#4096]
It seems like `libelf-dev` is missing.

When running `make` in `oak_containers_kernel` I get lots of errors saying `fatal error: gelf.h: No such file or directory`

**Comment by tiziano88** [comment]
That's because the nix shell for building containers-related stuff is separate. You can get it by running `nix develop .#containers`. Though I think I will merge it with the default one, and have a separate one for generic CI that does not include the containers stuff.

See https://github.com/project-oak/oak/blob/c84caa02bf8e606db5b081e038127d74d808e629/flake.nix#L144

**Comment by tiziano88** [comment]
I'll assign this to myself to merge the shells. Please let me know if the containers shell works for you though

**Comment by conradgrobler** [comment]
yes, it worked fine thanks.

**Comment by tiziano88** [comment]
I'll leave this open until #4097 is submitted
