### ISSUE TITLE
Oak SDK depends on Oak Runtime

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#473]
https://github.com/project-oak/oak/blob/17ea41af76c4202235269d7139a05cad4f24ced1/sdk/rust/Cargo.toml#L20

The runtime (internal) may depend on the SDK (external), but currently this is backwards.

@daviddrysdale is this dependency legit? Is there any ongoing refactoring that removes it already? 

/cc @blaxill

**Comment by blaxill** [comment]
This is for `oak_tests` I believe, which runs oak rust modules natively- instead of compiling them to Wasm, it provides rust functions for the Wasm host ABI functions. It in turn requires access to some form of runtime. Originally `oak_runtime` was originally only for testing and lived in the SDK directory. In the process of making `oak_runtime` not test specific (i.e. code to be used in the server) it moved out of the SDK directory.

The dependency is from `sdk/rust/oak_tests`, which can't be removed. An alternative would be to move `sdk/rust/oak_tests` into a testing directory, e.g. we have `sdk`, `oak/{server,client}` and could add `tests/oak_tests`.

**Comment by daviddrysdale** [comment]
This is the `oak_tests` crate in the SDK using the `oak_runtime` crate as its runtime implementation:
```
% find sdk/rust -name \*.rs | xargs grep oak_runtime
sdk/rust/oak_tests/src/lib.rs:use oak_runtime::{proto, NodeMain, OakMessage, OakRuntime};
```
When we get as far as a pure Rust runtime, including a Wasm engine, we *should* be able to remove this linkage.

BTW, I don't think:

> The runtime (internal) may depend on the SDK (external)

should be true in general, as [previously discussed](https://github.com/project-oak/oak/pull/429#discussion_r364178457).  But there's a few things to do before that's actually true of the Rust runtime. (Obviously the C++ runtime doesn't depend on the Rust SDK!)

**Comment by tiziano88** [comment]
Why should it not be true? Of course it would be better if they don't depend on each other at all, and instead they both depend on another crate, but I think it would not be problematic for the runtime to depend on the SDK (hence the [_may_](https://tools.ietf.org/html/rfc2119#section-5)), but I would say that the SDK [_must not_](https://tools.ietf.org/html/rfc2119#section-2) depend on the runtime. Or did I miss your point @daviddrysdale ?

**Comment by daviddrysdale** [comment]
I think the confusion here might be because we thinking about two slightly different aspects of the Oak SDK.

- The main part is the collection of code that gets compiled to Wasm and linked into the Oak Application (basically the `oak` and `oak_log` crates); call this the **Oak Wasm SDK**.
- The other part includes anything else that helps with the process of Oak software development; call this the **Oak SDK helpers**. At the moment this is:
   - `oak_tests`: functionality to help use the Rust runtime for testing Nodes
   - `oak_utils`: helpers to deal with building protobufs etc.

The runtime should not depend on the Oak Wasm SDK because it's a layering violation.  In the overall stack, things should only depend on the parts below them:
```
+------------+
|  Oak Node  |
+------------+
|  Wasm SDK  |
+------------+
=====ABI======
+------------+
|  Runtime   |
+------------+
=====EAL======
+------------+
| Enclave/OS |
+------------+
```
Along the way there are some specific interface boundaries, which gives rise to the title of this issue: the Wasm SDK should not depend *directly* on the Runtime, it should only depend on those features of the Runtime that are made available as part of the explicit ABI interface. (Not least because the Wasm SDK would then stop working if the C++ Runtime were providing the ABI.)

This isn't a concern for the SDK helpers, because they're not compiled into that layering stack. In particular:
- `oak_tests` is explicitly test code, and needs to directly drive the (Rust) runtime to allow test-only functionality (like injection of messages and/or faults). 
- `oak_utils` includes build-time utilities that are useful anywhere Rust code uses protobufs, both above and below the (ABI) line.

So  `sdk/oak_tests` -> `oak_runtime`  and `oak_runtime` -> `sdk/oak_utils` are both fine as dependencies without breaking layering.

**Comment by tiziano88** [comment]
This is still a problem (not sure if it was always, or is a recent regression): 

https://github.com/project-oak/oak/blob/a51d7f3bbbe4a96d43749cce996b9037213fd54f/sdk/Cargo.lock#L726-L727

It seems that the SDK still depends on the Runtime, via `oak_tests`.

**Comment by daviddrysdale** [comment]
Wasn't this always the case, as described in the [comment above](https://github.com/project-oak/oak/issues/473#issuecomment-590835636)?  
> `oak_tests` is explicitly test code, and needs to directly drive the (Rust) runtime to allow test-only functionality (like injection of messages and/or faults).

**Comment by tiziano88** [comment]
Yes I noticed afterwards, but it still feels off. If we published the SDK as a crate, it seems unreasonable for it to pull in the entire `oak_runtime`. At the very least it should be a `dev-dep` I guess, but would it be even better to instead have those tests in the `oak_runtime` crate itself?

**Comment by daviddrysdale** [comment]
I think #1038 would mostly make the `<example>/integration_test` -> `oak_tests` -> `oak_runtime` link go away:
 - The `grpc_request()` helper will become irrelevant, and can be deleted.
 -  The `run_single_module[_default]` helpers could be altered to just return the relevant configs (or moved over to `oak_runtime`), and then the examples' integration tests would just take the returned configs and feed them into `oak_runtime::configure_and_run`, leaving a dep graph of `oak_tests` <- `integration_test` -> `oak_runtime`.

**Comment by daviddrysdale** [comment]
On thinking/playing, ignore the previous comment.  The configs needed for `oak_runtime::configure_and_run` are types from the `oak_runtime` crate anyway, so the `oak_tests` -> `oak_runtime` dep would remain (and I don't think it would make sense to add test-only methods for building configs to `oak_runtime`).

**Comment by conradgrobler** [comment]
> Yes I noticed afterwards, but it still feels off. If we published the SDK as a crate, it seems unreasonable for it to pull in the entire `oak_runtime`. At the very least it should be a `dev-dep` I guess, but would it be even better to instead have those tests in the `oak_runtime` crate itself?

I have been looking into this, but I am not clear on the expected outcome. Do you want the `oak_tests` crate to be removed and the test features moved into`oak_runtime`? 

Regarding the dependency between the SDK and the runtime, the SDK has the following dev-dependencies that do not seem to be required (or am I missing something?):
```
oak_tests = "=0.1.0"
serial_test = "*"
serial_test_derive = "*"
```
If these are removed, the dependency on the runtime is only required when someone explicitly uses the `oak_tests` crate to test code in a wasm node inthe context of the runtime, which seems like it would always be needed.

**Comment by daviddrysdale** [comment]
>  the SDK has the following dev-dependencies that do not seem to be required

I suspect the `dev-dependencies` are left over from when the `oak` crate included unit tests.  They were removed in #472 and #544 raised to cover their reinstatement, but at this point I think it makes sense to close #544 (and to remove the `dev-dependencies` regardless).

**Comment by conradgrobler** [comment]
After merging #1242 I believe this is as decoupled as it can be for now.
