### ISSUE TITLE
Aggregator example

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#619]
After talking to @tiziano88 we decided to implement a new example application - Aggregator.

A possible application may look like this:
- Users can send histograms with data (probably need to implement a `Histogram` trait to support different types of histograms)
- Users can also request an aggregated histogram, but only if there is enough aggregated data

Another possible application is a `web_hit_counter`:
- Each user can send a string with a website that he has visited
- An application aggregated popularity of different websites (just strings in our case)
- Users can request an aggregated statistics, but only if there is enough data to hide individual users

**Comment by tiziano88** [comment]
The aggregator should work on anything that is conceptually a [semigroup](https://en.wikipedia.org/wiki/Semigroup), i.e. it has an associative operation to combine elements together (aggregation, in this case). For practical purposes, I think it makes sense to extend the example to a [monoid](https://en.wikipedia.org/wiki/Monoid), i.e. a semigroup with an identity element (so that we can easily represent the starting point of the aggregation). So overall, I think all this may be abstracted by a Rust trait:

```rust
trait Monoid {
  fn identity() -> Self;
  fn combine(&self, other: &Self) -> Self;
}
```

and then implement a node parametrized by this trait, for instance

```rust
struct Aggregator<T: Monoid> {
  // ...
}
```

which would be instantiated as a gRPC Node or similar. We would probably require type bounds to enforce that the aggregated type is also serializable and deserializable (e.g. to / from protobuf, or just a vector of bytes).

Additionally, it would be nice to implement a simple thresholding function, so that the node can be instantiated with a minimum number of entries, which it keeps track of internally, and only release aggregated data if the threshold is reached (it may return either an `Option::None` or the identity value of the Monoid otherwise).

**Comment by seefeldb** [comment]
Nice! For future iterations, we might want

- [ ] per item thresholds, possibly somewhat randomized
- [ ] restricting who can request aggregates

**Comment by tiziano88** [comment]
> Nice! For future iterations, we might want
> 
> * [ ]  per item thresholds, possibly somewhat randomized

Ideally this will be based on some actual differential privacy algorithm. The issue with a naive approach is that if you allow unlimited sampling, even adding random noise does not help that much, so we need to introduce linearity (only use once) or a privacy budget of some sort, which once exhausted prevents any further sampling.

> * [ ]  restricting who can request aggregates

This should be fulfilled by the labelling system, but yes we should clarify what it would look like in practice. For this example, we assume that the resulting aggregated data is effectively "public".

**Comment by benlaurie** [comment]
On Tue, 18 Feb 2020 at 16:02, Tiziano Santoro <notifications@github.com>
wrote:

> The aggregator should work on anything that is conceptually a semigroup
> <https://en.wikipedia.org/wiki/Semigroup>, i.e. it has an associative
> operation to combine elements together (aggregation, in this case). For
> practical purposes, I think it makes sense to extend the example to a
> monoid <https://en.wikipedia.org/wiki/Monoid>, i.e. a semigroup with an
> identity element (so that we can easily represent the starting point of the
> aggregation). So overall, I think all this may be abstracted by a Rust
> trait:
>
> trait Monoid {
>   fn identity() -> Self;
>   fn combine(&self, other: &Self) -> Self;
> }
>
> and then implement a node parametrized by this trait, for instance
>
Is it true that all aggregators can be implemented as a pairwise operation?
Seems like, for example, a neural network would be hard to fit into this
model...

**Comment by tiziano88** [comment]
> Is it true that all aggregators can be implemented as a pairwise operation? Seems like, for example, a neural network would be hard to fit into this model...

Are you talking about combining partial updates from clients participating to a federated learning system? If so, I think the partial updates can still be combined together, my understanding is that the model is just a giant vector / matrix / tensor that can be summed component-wise.
