### ISSUE TITLE
Rust App Config Serializer

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#740]
We need to add a Rust version of the App Config Serializer for creating binary configuration files for Oak applications.
C++ version of the Serializer was implemented in https://github.com/project-oak/oak/pull/459 as a part of https://github.com/project-oak/oak/issues/412.

~~Blocks https://github.com/project-oak/oak/issues/723~~

**Comment by ipetr0v** [comment]
Currently I have not found that [Prost](https://github.com/danburkert/prost) allows to read `textproto` files and to serialize protobuf structures into files, compared to C++ ProtoBuf:
https://github.com/protocolbuffers/protobuf/blob/70fc0f0275389a99b0c654778ef937f904921be0/src/google/protobuf/text_format.h#L448-L452
https://github.com/protocolbuffers/protobuf/blob/70fc0f0275389a99b0c654778ef937f904921be0/src/google/protobuf/message_lite.cc#L466-L474

I will continue searching but another possibility is to use JSON/YAML as textual config files, use them to create Rust structures and then serialize everything with [Serde](https://serde.rs/) (Rust serialization).

cc @tiziano88

**Comment by daviddrysdale** [comment]
Why does this block #723?  There's nothing stopping us having a C++ tool that generates a binary serialized protobuf file that the Rust runtime can then read (language interoperability being the point of protobuf, after all).

**Comment by tiziano88** [comment]
I agree this does not block anything, the current C++ serializer should work perfectly for both the C++ and Rust runtime. We may want to have different scripts / Bazel rules to make it easier to invoke perhaps, in the short term.

**Comment by ipetr0v** [comment]
Deleted block

**Comment by tiziano88** [comment]
Probably worth starting work on this, since we know it will necessary for #1183 , @ipetr0v WDYT?

**Comment by ipetr0v** [comment]
We already have TOML files with example info:
https://github.com/project-oak/oak/blob/08c6a6048e55e5ee6435d992bb1577ec7625ccd0/examples/abitest/example.toml#L1-L12

Should this be a separate file with a list of Wasm files, or it's better to keep everything together?
I personally prefer a separate file, because in this case we could just have a file with URLs and no source code.

WDYT?

**Comment by tiziano88** [comment]
The example manifests are and should stay separate; they are used to organize how examples are built and run, including clients and other example-specific stuff.

We need an application config manifest that is essentially a replacement for the textproto application definition, and also allow specifying the mapping from names to files (which is currently provided via flags to the app serializer).

The example TOML file then should probably be modified so that it points to the example manifest file, which `runner` or whatever other mechanism would then pass to the app serializer, after having actually built the local Wasm modules (the app serializer does not build the modules directly)

This should be the first version.

Next, separately, we should add support for specifying a URL as the source for the modules.

**Comment by ipetr0v** [comment]
Should serialized files be put into an `out` (https://github.com/project-oak/oak/issues/719) directory, or it's better to create something inside `target`?

**Comment by tiziano88** [comment]
I think we should create an `out` dir as part of this. `target` is specific to Rust, I would leave it alone.
