### ISSUE TITLE
Do not return `ERR_CHANNEL_CLOSED` from orphaned channels

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#763]
When a node tries to read or write on a channel that has no outstanding writers or readers, respectively, it receives a `ERR_CHANNEL_CLOSED` error immediately, to signal that the operation can never succeed on that channel again.

This may be used by a malicious node as a covert channel to exfiltrate one bit of potentially secret information, bypassing any labelling / information flow restrictions.

I think we should remove this mechanism, at the cost of nodes not being able to detect orphaned channels.

Also, in some current examples, channel closure is used to signal the termination of the oak application to nodes connected to channels. I think in this case we should be able to return `ERR_TERMINATED` instead, which would prevent the covert channel, and still allow nodes to notice when the runtime is shutting down (which AFAICT is the only reason why a node would terminate).

https://github.com/project-oak/oak/blob/70da1899692a7ceb9eb0875fb3ee001645adb04e/oak/proto/oak_api.proto#L31

@daviddrysdale could you look into this, both for C++ and Rust? More importantly, it would be nice to have a test case that works for both, so that we can make sure there are no regression between the two versions.

cc @blaxill @aferr

**Comment by blaxill** [comment]
IIRC are a few ABI calls in the rust runtime missing returning `ERR_TERMINATED`, I can address this tomorrow.  

> which AFAICT is the only reason why a node would terminate 

This isn't true for short lived nodes?

**Comment by daviddrysdale** [comment]
I think that removing `ERR_CHANNEL_CLOSED` would be a mistake.

If a Node can't detect orphaned channels, then it has no way of garbage collecting those channels, nor any state that is associated with the channel.  In practical terms, this would effectively rule out whole classes of long-running applications, where the application's state would grow monotonically.  

I suspect this will also become more of a problem if/when we move to a distributed runtime; if the endpoints of a channel no longer share fate, then a failure of one end but not the other is going to be a common phenomenon, and losing the ability to signal that is going to be very problematic.

(At a more detailed level, the closure of a response channel is also currently used in gRPC processing, to indicate the completion of a server-streaming method, but that could be avoided at the cost of sending an extra 'close' message.)

On the `ERR_TERMINATED` front, I'm not aware of code that uses channel closure to indicate overall application termination.  If there is, we should fix it &ndash; the intent with `ERR_TERMINATED` was for the runtime to indicate shutdown to the whole application, as an external *force majeure* that's slightly more graceful than just dropping everything.  

(Aside: now we're not running a multi-Application runtime, we no longer habitually externally-terminate Applications, so it may be that just removing `ERR_TERMINATED` makes sense. )

I also think there's going to be various reasons why an individual Node might self-terminate, even if the Application carries on. 
 - An ephemeral node might receive a message and an onward channel, perform some transformation on the message and forward it down the channel, then close down &ndash; making it easy to show that no in-memory state of the operation remains.  This is likely to interact with declassification &ndash; if (say) an encryption node is allowed to remove labels, you probably still want to spin up a new Node instance for each operation.
 - A Node that no longer has any non-orphan channels might as well terminate, because all it can now do is burn CPU (e.g. Chat room Node where all participants have left).
