### ISSUE TITLE
Simplify channel identification in Rust runtime

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#797]
There are currently three different numeric values used to identify particular channels, or the ends thereof:

 - `ChannelId` identifies a channel, is runtime-wide, takes values that are assigned consecutively.  The core ownership of `Channel` objects is in a `HashMap` indexed by `ChannelId` (the `channels` field of `ChannelMapping`).
 - `runtime::Handle` identifies one half of a channel, is runtime-wide and takes values that are assigned randomly. It is a tuple `struct` that holds a single value of type `oak_abi::Handle` (but does not hold values that are valid on the ABI). The `readers` and `writers` fields in `ChannelMapping` track the correlation from `runtime::Handle` values to `ChannelId` values.
 - `oak_abi::Handle` identifies one half of a channel, is Node-specific and takes values that are assigned randomly. This is the "handle" concept that is described in all of the docs and interface specifications. The `WasmInterface` object used by the Wasm runtime code has `readers` and `writers` fields which track the correlation from `oak_abi::Handle` values to `runtime::Handle` values.

This setup is difficult to follow, and involves a fair amount of book-keeping to keep things in sync.  Various suggestions:

- Reserve the word "handle" for `oak_abi::Handle` values, to avoid confusion.  Always use "SomethingId" for other numeric identifiers for channels.
- Don't use the `oak_abi::Handle` type for anything that is not an ABI handle; in particular, make the contents of a `runtime::Handle` a plain `u64` to avoid confusion.
- Drop the `runtime::Handle` type altogether, and just use `ChannelId` and `oak_abi::Handle` values to identify channels.  This will probably need additional use of the `HandleDirection` enum in combination with `ChannelId` when it is one particular half of a channel that needs to be identified.
- Drop the manual correlation between numeric identifiers for channels, and come up with a scheme that uses a standard library reference counting type to ensure that `Channel`s are dropped when the last `oak_abi::Handle` is closed.

**Comment by daviddrysdale** [comment]
For discussion, cc/ @tiziano88 @blaxill

**Comment by blaxill** [comment]
I agree on simplifying this.

> Drop the runtime::Handle type altogether, and just use ChannelId and oak_abi::Handle values to identify channels. This will probably need additional use of the HandleDirection enum in combination with ChannelId when it is one particular half of a channel that needs to be identified.

I think this can be done with a simple replace of the runtime::Handle since it is a simple wrapper, I don't think . I do think there is some benefit to having opaque types for type safety, but since this is internal to the runtime I guess it will be mostly people somwhat familiar with Oak concepts working on it anyway so there is less benefit.

> Drop the manual correlation between numeric identifiers for channels, and come up with a scheme that uses a standard library reference counting type to ensure that Channels are dropped when the last oak_abi::Handle is closed.

For context, they originally were using `Arc`. Assuming you only use `oak_abi::Handle` and it is a plain `u64`, it's unclear to me how you would apply any of the standard library reference counting types. You could change `ChannelMapping` to say

~~~
pub struct ChannelMapping {
    pub channels: RwLock<Vec<Arc<Channel>>>, 
    pub readers: RwLock<HashMap<Handle, Arc<Channel>>>,
~~~

but I'm not sure you gain anything over the numeric situation- to track when channels are orphaned you still need the `writers`/`reader` members of `Channel` (whether they are `AtomicU64` or something else like self inserted Handles `Mutex<Vec<Handle>>`), and so you end up with having the components for manual tracking but don't use them for garbage collection. 

This is opinionated though, and I think any direction is fine (including the `Arc`s above). I personally lean towards abstracting out the generic parts of the channel reference counting to simplify it if needed.

Another alternative could be something like a reference counted arena (supporting deallocation). I previously had a cursory look at this kind of thing but didn't find anything with the same goals in mind.

**Comment by tiziano88** [comment]
> * Drop the `runtime::Handle` type altogether, and just use `ChannelId` and `oak_abi::Handle` values to identify channels.  This will probably need additional use of the `HandleDirection` enum in combination with `ChannelId` when it is one particular half of a channel that needs to be identified.

I think we should consider introducing the concept of "rights", so that a handle in the context of a node is associated with some rights over an underlying object (identified by its id). In our case, rights may be "read" and "write", but we can imagine "wait", "close" or "duplicate" to be additional rights at some point in the future, giving finer-grain control over capabilities.

Note we don't need to expose this concept at the ABI level at all yet, I'm just suggesting as an internal implementation detail, but in the future we could consider externalizing it if we want to.

For reference, Fuchsia also has this concept: https://fuchsia.dev/fuchsia-src/concepts/kernel/rights .

> * Drop the manual correlation between numeric identifiers for channels, and come up with a scheme that uses a standard library reference counting type to ensure that `Channel`s are dropped when the last `oak_abi::Handle` is closed.

I am not so sure about this. I would prefer that the Runtime be the ultimate single owner of all the objects (i.e. channels and nodes); anything else that is given to nodes should be in the form of a numeric identifier or weak reference, and should be resolved by the Runtime into an actual reference to the underlying object, which allows it to enforce additional properties (e.g. information flow). This also allows for revocation if we wanted to implement that at some point.

**Comment by daviddrysdale** [comment]
> I am not so sure about this. I would prefer that the Runtime be the ultimate single owner of all the objects (i.e. channels and nodes); anything else that is given to nodes should be in the form of a numeric identifier or weak reference, and should be resolved by the Runtime into an actual reference to the underlying object, which allows it to enforce additional properties (e.g. information flow). This also allows for revocation if we wanted to implement that at some point.

I agree that Nodes &ndash; whether 3p Wasm nodes or 1p pseudo-Nodes &ndash; should only deal in `oak_abi::Handle` values; I'm purely talking about within the runtime codebase itself. 

In that context, my fundamental concern is that we're doing an awful lot of manual cross-reference tracking, which is inevitably error-prone and hard to maintain.  

It would be better if we were able to rely on a standard library feature (like `Arc`) that's type-safe, heavily tested and well-documented.

That's not immediately possible, because we need to keep track of reader and writer counts to be able to detect orphaned channels<sup>1</sup>, but I think we can come up with some combination of `Arc`-ified data structures that do both (automatically handle lifetime, while still allowing orphan detection).  To some degree, the data structures of the C++ runtime are an existence proof that this is possible.

<hr/>
1: Where I still disagree with #763, even though it would make this vastly easier.
