### ISSUE TITLE
Identify Oak Wasm modules by hash

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#804]
Replace the raw bytecode included in the `ApplicationConfiguration` with just a hash of the bytecode to instantiate, and pass the actual bytecode to the Oak Manager in some other way.

**Comment by tiziano88** [comment]
Somewhat related to #688 and #689 .

How about the following:

- introduce an `ApplicationArchive` protobuf object, with a schema similar to

  ```proto
  message ApplicationArchive {
    // Maps names to wasm bytecode.
    map<string, bytes> wasm_modules = 1;
  }
  ```

- Slightly modify the `NodeConfiguration` object:

  https://github.com/project-oak/oak/blob/c2b2ff4b666de2a4f5fe7ff7cbfadbfc00af69f2/oak/proto/application.proto#L43-L52

  + add a `GrpcServerConfiguration` message
  + modify `WebAssemblyConfiguration` to refer to the *name* of one of the wasm modules, rather than have the bytes inlined:

     https://github.com/project-oak/oak/blob/c2b2ff4b666de2a4f5fe7ff7cbfadbfc00af69f2/oak/proto/application.proto#L54-L61

     effectively replace `bytes module_bytes` with `string wasm_module_name`

- modify the `oak_loader` binary to have two flags to specify an `ApplicationArchive` and an `ApplicationConfiguration`, respectively. The idea is that the same modules may be instantiated in a number of different ways (e.g. local vs dev vs prod), just by using a different `ApplicationConfiguration`, which does not contain any actual executable code.
