### ISSUE TITLE
Implement gRPC client pseudo-node in Rust runtime

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#844]
Similar to the existing C++ implementation: https://github.com/project-oak/oak/blob/2f257f2b32286bef1615c44bceb3a413346c5919/oak/server/grpc_client_node.h .

@ipetr0v have you looked into this already by any chance, as part of the gRPC server pseudo-node work?

**Comment by ipetr0v** [comment]
I haven't looked much into this, but I think we will be able to use [`tonic::client`](https://docs.rs/tonic/0.2.0/tonic/client/index.html)

**Comment by ipetr0v** [comment]
Since `tonic` uses `rustls` (that doesn't support checking certificates using IP addresses https://github.com/ctz/rustls/issues/184) we will only be able to connect to a gRPC service by its domain name:
https://github.com/hyperium/tonic/blob/f6ecaff0de76de16cb1f680dc3473c8cf2bbaddd/examples/src/tls/client.rs#L13-L15

**Comment by ipetr0v** [comment]
Also, do we need to authenticate a gRPC client Node to for an external gRPC service?
Probably can be a separate PR (if we need this feature).
