### ISSUE TITLE
Rename `public_trusted` label to `public_untrusted`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#980]
https://github.com/project-oak/oak/blob/11f96d62555364286881e3cc081c98d5754c5f19/oak/server/rust/oak_abi/src/label/mod.rs#L47-L55

I think the (incorrect) `public_trusted` naming was due to my misunderstanding of the IFC lattice structure in some early discussions with @aferr . 

@aferr to clarify: this label is the least privileged (in [Flume](https://pdos.csail.mit.edu/papers/flume-sosp07.pdf) terms, it has empty confidentiality and integrity components) so I believe it should be called `public_untrusted`, right? Or should we call it `bottom`, or something else?

Aside: if anything, `public_trusted` is perhaps the label that the oak runtime itself would have, if it had one (though it does not have an explicit one currently), since it is indeed trusted by clients, e.g. over gRPC, thanks to remote attestation (but that's another discussion anyways).

**Comment by aferr** [comment]
You are right that this is public_untrusted based on the Flume model.

In the conventional "information flow lattice", public_untrusted is not the bottom element, public_trusted is. This is also true for Flume.

Just to show why public_trusted is the bottom element, the conventional 4-point public/secret, trusted/untrusted lattice is:

                                    secret_trusted
        public_untrusted                            secret_trusted
                                   public_trusted

And allowed flow of information is "upwards".

I think you are right that public_trusted (the bottom element in the information flow order) should be the label of the oak runtime (if that really is a thing that has a label), but IDK if you have an easy way to express that in your system yet since "trusted" needs to be the set of all the tags! (Some possible designs we have been talking about involving extensionally defined lattices would fix this issue. Easier solutions than a DSL for labels might be better if you have one.)

----------------------------------------------------
Bonus material to try to help un-confuse:

You might be (very reasonably) confused about why public_untrusted is not the bottom element after having looked at FLAM. FLAM is very confusing (to everyone). FLAM is very different from the above well-established lattice. FLAM has an authority lattice and an information flow lattice, and the authority lattice is rotated 90 degrees so that public_untrusted is the bottom element in the authority lattice. (though there are other nice things about FLAM).
